// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdjustGoalRequestDirection.
const (
	Deposit  AdjustGoalRequestDirection = "deposit"
	Withdraw AdjustGoalRequestDirection = "withdraw"
)

// Valid indicates whether the value is a known member of the AdjustGoalRequestDirection enum.
func (e AdjustGoalRequestDirection) Valid() bool {
	switch e {
	case Deposit:
		return true
	case Withdraw:
		return true
	default:
		return false
	}
}

// Defines values for CreateTransactionRequestKind.
const (
	CreateTransactionRequestKindExpense CreateTransactionRequestKind = "expense"
	CreateTransactionRequestKindIncome  CreateTransactionRequestKind = "income"
)

// Valid indicates whether the value is a known member of the CreateTransactionRequestKind enum.
func (e CreateTransactionRequestKind) Valid() bool {
	switch e {
	case CreateTransactionRequestKindExpense:
		return true
	case CreateTransactionRequestKindIncome:
		return true
	default:
		return false
	}
}

// Defines values for CreateTransactionRequestPaymentMethod.
const (
	CreateTransactionRequestPaymentMethodCard  CreateTransactionRequestPaymentMethod = "card"
	CreateTransactionRequestPaymentMethodDebit CreateTransactionRequestPaymentMethod = "debit"
	CreateTransactionRequestPaymentMethodPix   CreateTransactionRequestPaymentMethod = "pix"
)

// Valid indicates whether the value is a known member of the CreateTransactionRequestPaymentMethod enum.
func (e CreateTransactionRequestPaymentMethod) Valid() bool {
	switch e {
	case CreateTransactionRequestPaymentMethodCard:
		return true
	case CreateTransactionRequestPaymentMethodDebit:
		return true
	case CreateTransactionRequestPaymentMethodPix:
		return true
	default:
		return false
	}
}

// Defines values for SessionResponseTokenType.
const (
	Bearer SessionResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionResponseTokenType enum.
func (e SessionResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for TransactionResponseKind.
const (
	TransactionResponseKindExpense TransactionResponseKind = "expense"
	TransactionResponseKindIncome  TransactionResponseKind = "income"
)

// Valid indicates whether the value is a known member of the TransactionResponseKind enum.
func (e TransactionResponseKind) Valid() bool {
	switch e {
	case TransactionResponseKindExpense:
		return true
	case TransactionResponseKindIncome:
		return true
	default:
		return false
	}
}

// Defines values for TransactionResponsePaymentMethod.
const (
	TransactionResponsePaymentMethodCard  TransactionResponsePaymentMethod = "card"
	TransactionResponsePaymentMethodDebit TransactionResponsePaymentMethod = "debit"
	TransactionResponsePaymentMethodPix   TransactionResponsePaymentMethod = "pix"
)

// Valid indicates whether the value is a known member of the TransactionResponsePaymentMethod enum.
func (e TransactionResponsePaymentMethod) Valid() bool {
	switch e {
	case TransactionResponsePaymentMethodCard:
		return true
	case TransactionResponsePaymentMethodDebit:
		return true
	case TransactionResponsePaymentMethodPix:
		return true
	default:
		return false
	}
}

// AdjustGoalRequest defines model for AdjustGoalRequest.
type AdjustGoalRequest struct {
	AmountMinor int64                      `json:"amountMinor"`
	Direction   AdjustGoalRequestDirection `json:"direction"`
}

// AdjustGoalRequestDirection defines model for AdjustGoalRequest.Direction.
type AdjustGoalRequestDirection string

// CategoryTotalResponse defines model for CategoryTotalResponse.
type CategoryTotalResponse struct {
	Category   string `json:"category"`
	TotalMinor int64  `json:"totalMinor"`
}

// CreateGoalRequest defines model for CreateGoalRequest.
type CreateGoalRequest struct {
	Name        string `json:"name"`
	TargetMinor int64  `json:"targetMinor"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// CreateTransactionRequest O formato antigo com apenas amountMinor e necessityLevel permanece como despesa legada. Novos lançamentos exigem kind, description, category, occurredAt e installments; despesas exigem paymentMethod e necessityLevel. Receita não aceita necessityLevel ou paymentMethod e deve ter uma parcela. Parcelamento é apenas um atributo informativo; não cria faturas ou cobranças.
type CreateTransactionRequest struct {
	// AmountMinor Valor positivo em unidades menores. A moeda do produto ainda precisa ser definida; não misturar moedas.
	AmountMinor    int64                                  `json:"amountMinor"`
	Category       *string                                `json:"category,omitempty"`
	Description    *string                                `json:"description,omitempty"`
	Installments   *int                                   `json:"installments,omitempty"`
	Kind           *CreateTransactionRequestKind          `json:"kind,omitempty"`
	NecessityLevel *int                                   `json:"necessityLevel,omitempty"`
	OccurredAt     *time.Time                             `json:"occurredAt,omitempty"`
	PaymentMethod  *CreateTransactionRequestPaymentMethod `json:"paymentMethod,omitempty"`
}

// CreateTransactionRequestKind defines model for CreateTransactionRequest.Kind.
type CreateTransactionRequestKind string

// CreateTransactionRequestPaymentMethod defines model for CreateTransactionRequest.PaymentMethod.
type CreateTransactionRequestPaymentMethod string

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`

	// Name Example: Kaian
	Name string `json:"name"`

	// Password Ao menos 8 caracteres, com letras maiúsculas e minúsculas, número e caractere especial.
	Password *string `json:"password,omitempty"`
}

// DashboardResponse defines model for DashboardResponse.
type DashboardResponse struct {
	ExpenseMinor       int64                   `json:"expenseMinor"`
	ExpensesByCategory []CategoryTotalResponse `json:"expensesByCategory"`
	GoalsSavedMinor    int64                   `json:"goalsSavedMinor"`
	GoalsTargetMinor   int64                   `json:"goalsTargetMinor"`
	IncomeMinor        int64                   `json:"incomeMinor"`

	// Month Example: 2026-09
	Month              string                `json:"month"`
	NetTrackedMinor    int64                 `json:"netTrackedMinor"`
	RecentTransactions []TransactionResponse `json:"recentTransactions"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Example: Dados de entrada inválidos
	Message string `json:"message"`
}

// GoalResponse defines model for GoalResponse.
type GoalResponse struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	SavedMinor  int64              `json:"savedMinor"`
	TargetMinor int64              `json:"targetMinor"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// ListGoalsResponse defines model for ListGoalsResponse.
type ListGoalsResponse struct {
	Data   []GoalResponse `json:"data"`
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
}

// ListTransactionsResponse defines model for ListTransactionsResponse.
type ListTransactionsResponse struct {
	Data   []TransactionResponse `json:"data"`
	Limit  int                   `json:"limit"`
	Offset int                   `json:"offset"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Data   []UserResponse `json:"data"`
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Token Segredo de sessão; não armazenar em logs.
	Token     string                   `json:"token"`
	TokenType SessionResponseTokenType `json:"tokenType"`
}

// SessionResponseTokenType defines model for SessionResponse.TokenType.
type SessionResponseTokenType string

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	AmountMinor  int64                   `json:"amountMinor"`
	Category     string                  `json:"category"`
	CreatedAt    time.Time               `json:"createdAt"`
	Description  string                  `json:"description"`
	Id           openapi_types.UUID      `json:"id"`
	Installments int                     `json:"installments"`
	Kind         TransactionResponseKind `json:"kind"`

	// NecessityLevel Apenas despesas.
	NecessityLevel *int                              `json:"necessityLevel,omitempty"`
	OccurredAt     time.Time                         `json:"occurredAt"`
	PaymentMethod  *TransactionResponsePaymentMethod `json:"paymentMethod,omitempty"`
}

// TransactionResponseKind defines model for TransactionResponse.Kind.
type TransactionResponseKind string

// TransactionResponsePaymentMethod defines model for TransactionResponse.PaymentMethod.
type TransactionResponsePaymentMethod string

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Email Example: kaian.gabriel@example.com
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Example: Kaian Gabriel
	Name *string `json:"name,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`

	// Name Example: Kaian
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RecordID defines model for RecordID.
type RecordID = int64

// GetDashboardParams defines parameters for GetDashboard.
type GetDashboardParams struct {
	// Month Mês em UTC, padrão é o mês atual.
	Month *string `form:"month,omitempty" json:"month,omitempty"`
}

// ListGoalsParams defines parameters for ListGoals.
type ListGoalsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Quantidade máxima de usuários na página.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Quantidade de usuários a pular antes de iniciar a página.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateGoalJSONRequestBody defines body for CreateGoal for application/json ContentType.
type CreateGoalJSONRequestBody = CreateGoalRequest

// AdjustGoalJSONRequestBody defines body for AdjustGoal for application/json ContentType.
type AdjustGoalJSONRequestBody = AdjustGoalRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetDashboard Resumo dos lançamentos rastreados do titular
	// (GET /dashboard)
	GetDashboard(c *gin.Context, params GetDashboardParams)
	// ListGoals Lista metas virtuais do titular
	// (GET /goals)
	ListGoals(c *gin.Context, params ListGoalsParams)
	// CreateGoal Cria uma meta com saldo virtual inicial zero
	// (POST /goals)
	CreateGoal(c *gin.Context)
	// AdjustGoal Ajusta saldo virtual, sem transferir dinheiro
	// (POST /goals/{id}/allocations)
	AdjustGoal(c *gin.Context, id openapi_types.UUID)
	// GetHealth Verifica a saúde da aplicação
	// (GET /health)
	GetHealth(c *gin.Context)
	// CreateSession Autentica um usuário e cria uma sessão de 24 horas
	// (POST /sessions)
	CreateSession(c *gin.Context)
	// ListTransactions Lista transações do titular autenticado
	// (GET /transactions)
	ListTransactions(c *gin.Context, params ListTransactionsParams)
	// CreateTransaction Cria uma transação para o titular autenticado
	// (POST /transactions)
	CreateTransaction(c *gin.Context)
	// ListUsers Consulta somente o perfil autenticado
	// (GET /users)
	ListUsers(c *gin.Context, params ListUsersParams)
	// CreateUser Cadastra um usuário
	// (POST /users)
	CreateUser(c *gin.Context)
	// UpdateUser Atualiza os dados de um usuário
	// (PATCH /users/{id})
	UpdateUser(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetDashboard(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", c.Request.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter month: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDashboard(c, params)
}

// ListGoals operation middleware
func (siw *ServerInterfaceWrapper) ListGoals(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGoalsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGoals(c, params)
}

// CreateGoal operation middleware
func (siw *ServerInterfaceWrapper) CreateGoal(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGoal(c)
}

// AdjustGoal operation middleware
func (siw *ServerInterfaceWrapper) AdjustGoal(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdjustGoal(c, id)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSession(c)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTransactions(c, params)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTransaction(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/sessions", wrapper.CreateSession)
	router.GET(options.BaseURL+"/transactions", wrapper.ListTransactions)
	router.POST(options.BaseURL+"/transactions", wrapper.CreateTransaction)
	router.GET(options.BaseURL+"/dashboard", wrapper.GetDashboard)
	router.GET(options.BaseURL+"/goals", wrapper.ListGoals)
	router.POST(options.BaseURL+"/goals", wrapper.CreateGoal)
	router.POST(options.BaseURL+"/goals/:id/allocations", wrapper.AdjustGoal)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.PATCH(options.BaseURL+"/users/:id", wrapper.UpdateUser)
}
