// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`

	// Name Example: Kaian
	Name string `json:"name"`

	// Password De 15 a 128 caracteres Unicode, preservando espaços e sem regras de composição.
	Password *string `json:"password,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Example: Dados de entrada inválidos
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`

	// Name Example: Kaian
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Verifica a saúde da aplicação
	// (GET /health)
	GetHealth(c *gin.Context)
	// CreateUser Cadastra um usuário
	// (POST /users)
	CreateUser(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFZPb9vGE/0qi/n9jrT+2HHh8lTHSVojBWoEdS+BDhPuSFqH3N3MLBULAT+M0UNO/QK96osVu6Qki1Ra",
	"BDB8o4SdmTfvvX3kFyhc5Z0lGwTyLyDFkipMj1dMGOhWiN/Rp5okxD89O08cDKUjVKEp08M9Vr4kyOEj",
	"GrQ/db9Hhasgg7njCgPk3fkMwtrHsxLY2AU0GVis6LDP29gHMqiM/ZXsIiwhnx4p9Cjy2bGOxZqkYOOD",
	"cRZyeEVqeq5QTU8vVIGMRSAmUbfWFE5TpjyTEK/QaqdIPG6+OlGkhCrFtGAUpUklcsRsvm7+dKPHm+zm",
	"ZlDh/Q7h6cUh4vM+5Aw+swn0my3XkAeuqWkyYPpUGyYN+fuWiWzH1G7ObNfJfbijIsTlXzM7fkfinRUa",
	"qlORCC56vL5C7dJqZAOjRmXsavNQGu1kKEwP27bhMSy/EJZh+W0wEjDUcojFffzPkV3ZsYmtM/fzUGsT",
	"tcfy5tHkOZZCWQ9MkaytL5Old5pqDHQSTOJ/YLQns7rRB0Pr2ujvuxGDo7XX37dNj+MEoOe7PUOP+w9l",
	"iL2Mnbvh/bu8uVYeGdWCmGxhsCIbnJobi7Ygwy7iMiGt9sbYS+/V5c01ZLAilrbFZDQdTeKGzpNFbyCH",
	"s9FkdJbuRVgmKcfLZLz4uKDEQBQaI4hrDTn8TKG1JsSlW7ekwtPJJFnB2UA2FaL3pSlS6fhOIoJtHsan",
	"/zPNIYf/jfeBOe7Sctwzf2Klx0ZqnXJEaRPPbf5aUZm0kLqqkNeQwx/EZm4KVKgEN39rUhoV7ksjZbiQ",
	"KFq31Cw2GNdCnJbyTo5wsE9yaJUnCS+dXj/Z/sNXRXNospR0AwGmTwbgIAuO0H8r9eaBjVMFG9QueurF",
	"E+p/GMRH5v9b6iYsPz4fltcn8Y6ru82DKlCjREAtI9Oz50Nx5di7aO9kku4Vq+i+IE3qhxfqrXnZYjp/",
	"Tkxpysnva09K0yp+DbAaDGwyOH9O87zBchkdE4gt9hLjqlNQ1ZWqO5M/SonbFAyz1DR+7aSYeD+I6uqD",
	"IRtIla7AmP41l5DDMgSfj8fpz6WTkF9MLibQzHbt+3228dXF3LdDrH25bTOsyfqNuq1cvDHbrWRf127V",
	"zJp/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
