// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SessionResponseTokenType.
const (
	Bearer SessionResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionResponseTokenType enum.
func (e SessionResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	// AmountMinor Valor em unidades monetárias menores (ex. centavos). Moeda a ser definida no contrato do produto.
	AmountMinor    int64 `json:"amountMinor"`
	NecessityLevel int   `json:"necessityLevel"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`

	// Name Example: Kaian
	Name string `json:"name"`

	// Password Ao menos 8 caracteres, com letras maiúsculas e minúsculas, número e caractere especial.
	Password *string `json:"password,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Example: Dados de entrada inválidos
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// ListTransactionsResponse defines model for ListTransactionsResponse.
type ListTransactionsResponse struct {
	Data   []TransactionResponse `json:"data"`
	Limit  int                   `json:"limit"`
	Offset int                   `json:"offset"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Data   []UserResponse `json:"data"`
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Token Segredo de sessão; não armazenar em logs.
	Token     string                   `json:"token"`
	TokenType SessionResponseTokenType `json:"tokenType"`
}

// SessionResponseTokenType defines model for SessionResponse.TokenType.
type SessionResponseTokenType string

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	AmountMinor    int64              `json:"amountMinor"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	NecessityLevel int                `json:"necessityLevel"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Email Example: kaian.gabriel@example.com
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Example: Kaian Gabriel
	Name *string `json:"name,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Email Example: kaian@example.com
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`

	// Name Example: Kaian
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Quantidade máxima de usuários na página.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Quantidade de usuários a pular antes de iniciar a página.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Verifica a saúde da aplicação
	// (GET /health)
	GetHealth(c *gin.Context)
	// CreateSession Autentica um usuário e cria uma sessão de 24 horas
	// (POST /sessions)
	CreateSession(c *gin.Context)
	// ListTransactions Lista transações do titular autenticado
	// (GET /transactions)
	ListTransactions(c *gin.Context, params ListTransactionsParams)
	// CreateTransaction Cria uma transação para o titular autenticado
	// (POST /transactions)
	CreateTransaction(c *gin.Context)
	// ListUsers Lista usuários com paginação
	// (GET /users)
	ListUsers(c *gin.Context, params ListUsersParams)
	// CreateUser Cadastra um usuário
	// (POST /users)
	CreateUser(c *gin.Context)
	// UpdateUser Atualiza os dados de um usuário
	// (PATCH /users/{id})
	UpdateUser(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSession(c)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTransactions(c, params)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTransaction(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/sessions", wrapper.CreateSession)
	router.GET(options.BaseURL+"/transactions", wrapper.ListTransactions)
	router.POST(options.BaseURL+"/transactions", wrapper.CreateTransaction)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.PATCH(options.BaseURL+"/users/:id", wrapper.UpdateUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FrNchu5EX6VLiSHpGpMUbK8pTCXyPbuRrXaWsWScnHp0Bo0SdgDYAxgtJJVfBhlDz7tMRdf58VSAIbD",
	"Gc5QlByJ8lb5JHI0aDT65+uvG7xmqZa5VqScZaNrZtMpSQwfXxlCR8dkrdDqDX0oyDr/HDkXTmiF2ZHR",
	"ORknyLLRGDNLCcsbj64ZSRSZ/zDWRqJjo+pJwtxVTmzErDNCTdgsYTla+6s2vPV2/XB5QcJ+NcLRLyq7",
	"YiNnCprNEmboQyEMcTZ6W+9TSzirRejzd5Q6v2c84YlBZTF1X3xKlLpQ7mehtPFfOdnUiNwvZiP2b8y0",
	"AZJQKMGRkwWpFbnyxgi0IElpQxb+QpcDSEk5vND2rwP4WRNHQLBkgNNY+LWgNKRaOYNOA9eQG80Lpwcs",
	"WRhMKPfdLkuYFErIQrLRdn1soRxNyPhzK0q9V93VIV1Q8I/Ey/j+i9vXLlm5efKO2NUWP7VkGqZeETN0",
	"iTLP/Pr3KFD9o/o+SLVsHnllRCmU1Jbzk5cTrXNIauKmzTP2h2Lbmfs6eMzCHqRoMHVkyCaQagkZOeMd",
	"iqL8bNMiQwsEUqj5twRU+VmS0UCLtUA2p1Rg1nJiI+olXtaa7uy1NN+7d04EgyR3S43vjdHmDdlcK0td",
	"J0myFidL5n2NXFvgBOSDlCMIdVHeZIJr2/XPkm5zgX26/JMwc9PVyliHrrBtXfT7tVtWy/p2PBTWNWDB",
	"Nve+BzBwdOj/CkcyPPizoTEbsT9tLUB3q0LcrRYMVdvNQgQcxOXbw2GtKhqDV/7fmZDCtTI4vHZ7/uvx",
	"2FJcNX9vuDbXw2HmG9YyVlnPp/hGzBax5A9tr7rEfpG16DIXhuy+a1VOjo6eORESvgNwTr8n1UW3Y5oY",
	"4tpnsCVry9/030GVv2lAI/EjKQx1LNMTO1gp9SQ8vWakvJXespeEhkzj2CuSMarUFJI0TtZntb58+b/q",
	"dqeIdgMhDeWL38fWos1oikLw3mLVKclrwiuIubX+NtXtM+Bpzru1+FbzSaGaT7eTO5buwQTPjaDsoUo4",
	"/BjlrSvls75TN/HifvHyBd5/MDJz1zBayXk6rxbB/fc4TV8ALlGKhYWa8rvBN0uYpbQwwl0dexyP9j0P",
	"WLFfeGcuY9OJxwXQOaYa9LkTXHssOvrl+AS2bMTPgEqhLPitorDFKabO5WzmdxZqrHuo3dEB5GgQJmRI",
	"pQIlKadhLBSqlITRXpRwwaY/CLWf57B/dMASdkHGRhHDwfZgGOpFTgpzwUbs+WA4eB64lpuGM25NA5nx",
	"HyexpPgIQ6/EAWcj9iO5SHeYt3YM07BwZzgMMaiVIxVTNc8zkYalW++sVov2bV3NXCJUwSpL1giiy08e",
	"/bnw75W/e0wJniukRHPlexsyYizS0Khg+ZkT+KZlsdSbDCfWR0t1qDMvoHZYoHLa9pih1XuyGHhk3UvN",
	"rx7MCr397awd5oFGP6Inlkt/jyuOYymG1Ajk6MNr9wEVaPP8nu1faZPrBZOP+29vcH9DPOSjsLUWaIMa",
	"2883bQa6TIkTfLcLP4mXUYcXm9Qh7PLM0yPgdEFhPNDZcJawF5uMkB8wm/pez5FRuIQQ+4VXwENEIaGw",
	"RXljROiAjfCPcE40Pefc2YWpNmgbqHE8B4qIG67RkjUQtK3OG3LaKIT4cvmp/C+FttyCoZSUIwu5EdJD",
	"euzcOVmSOTqCXBsQfABH5c1EKLRwgR8F+oVBpATP6f0aDZmwDuP/fdlpo9dy+xgKgEFJjow/1zUTXtMP",
	"BZmreREd1Z3Cwi2cxlhkjo12hsk9GpZZ0r9B1YL07tAU2dfbnD0iCK7stnuCrXKNj5emgzcOi0fo1YgF",
	"soaljYPjvDZgYX1kJwtVQBcQ+qeqZjw1IlRsLwR/k+e9PfOhtQCMw5BXrdzlGpxwRYYGcA4nvMktWql2",
	"Nktu5RSNlx+VV/RMle/ELR4uenoHSl1nncxt/XQcIw4OG9PCrzePvpGOr5Z03BViXs25h2tEfmj97gk0",
	"npIUNpT0NVxkznysb1q14SQhNWQDHfGlrO6bVzGSU4mQV6XPkgRDtshcSJuKnPRzkygvTrphZzgcwDGp",
	"abibmKKdkgVVqBTBxjqWZkX5uxeqEAIuWbeC3oT5bpfXtI//rwKVC7deIMubSyFD3V4YQ9WH8ps8Oida",
	"qVxLKYQ8hkCgipxAKJEK/2Cdsl8zv2rP428nVrUtnoBVmfI/kpyJ90h5D8mKWn01DU7kK4vo8enWULsB",
	"HjFj1tET/9aj8pLmvHfDhKR9VdO18+m8Pww0RD8RDem/vwy6/G1zunz/TKLI4F15AylytF4h/UQEhPti",
	"8KEQVsRU/EZI7gkSryoPNocgPchQ84mta8FnYTiKLu0Zhu+7AjPx0RMWpSUloIFivOgCUJ5r2y3ai9ue",
	"dVX79PTgtW+6GpqGapdjmEpXxS6M/9vY0Sx8a24qYr17eIzr3mlteKB7Z4zDyodPgHMHr32c8DnazTXp",
	"q7O7w93N6VXbJlw6k4o/dpob6Bv4fgPfLxpB12BpFzG/BohDO2ku+vFxX56L0LhlOsWMJawwWXXBONra",
	"Cg+n2rrR3nBvyDzQVeI7vwysbs+qW7bVd2gV4lZXaN1OpiovYa6uVWgM2zS+FhEP2JVQj+mrZlib+WB+",
	"sbaexXeXH6IqP8ULU9u4MW1s3OqcZ2ez/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
