// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3Lb9zGuue/8qHnDCDh0u2WYwc5EgyMLDs+nnMce2z5YAaxByiRX7fKIVlMVbEjO6PtYNZ3OavrySJw",
	"gKyM2WQ5/Z/cv2RQXxXJIlnshyy1nMTZRO5usl7f+/GrH0exyAqRY67VaP/HUcEky1CjpH89w1jI5NF9",
	"83eCKpa80Fzko/3RowTyMlu8lzwWkAiQOONKSzGKRtx8XzB9OopGOctwtD/iySgaSfy+5BKT0b6WJUYj",
	"FZ9ixsyrp0JmTJvf5frL26NolPGcZ2U22t+LRvpNgfYrnKEcnZ+fm1epQuQKaZL3WPIMvy9RafOvWOQa",
	"c/qTFUXKY2ZmfPO1MtP+0Rv0LxKno/3Rf7jZbMBN+626+UBKIZ+5QeyQ7eXfZ4lQwPP54l3KzZ+iNFsg",
	"GSQIOc4WH2IuYM5FyhIGOxnmis0wA8ygEFKXs3Lxi9odnUejR7lGmbOUhtzeAr5m6SkDbgc38/hG6K9F",
	"mSfbm8I3i58EYG4GkywRkdnDAqXGPEZgIEotBZSqXLyTXJgpvshZqU+F5G9xi9N8jkqZmbJSYa4xqk/d",
	"TBHwrOCSJWxkHnTvNEMexrEoc/13bne0/UqmFGrYYZrPRQR4NgazFGb46ITlsdgFJTIGuQAtNEsPIOXs",
	"hKdcv4GdgilVPzZlupT0XMykXvxknixPtGR8FI0wNxz0rR1tFI3ql4xe1VyltOT5zGyum7DHSYUU5ji4",
	"5bJTpv4bx9StZsrKVI/2pyxV2N8wYG5BEvMEYUctPgDPLZfzudgdw1O7CsjLPHY/G4/qWZ0IkSLLzbS+",
	"cxu47Aj9vT6vZM6PIzxjWZGa931TnrD8OytX/oH5TJ/6kqXag3NfRH1rX+Mm0GyYOHmNsW5tmCOd3o7F",
	"EpnG5FC3RFzCNN7QnN7dOwR/k/t7wZOgsOwKyI/atOV7QnLc3xhvypG34OB+Ja9LpR8Klno0xpKEG7Jh",
	"6VNv7xxZtbeTZWa+j3luxeRGOiMaJVxibAn0x5ozEiyE4oY3fuD6NJHshwBrdLageVHUmlJwyTI+5XNM",
	"hmmEuV/0ZYTRkXAXNM9PGZxypRcfSNciTAUHJr8v+Zwl4gBos+Cu/bhgM5aIACd1VlGPG5r2PZ6mPJ89",
	"yLV88ygvyoA0YJZ6Hq1LkXan+qt8ztJEQFLJC8wgxlyzuVAHwCrxNmcc6KD4nMGOAM0L75mEv4XvS6wE",
	"3+4oWkIbk4A90dmZemX1rFft0ZLj3XSb2lpjA/51T37j2LijaUWGzYblDBbvCxGzjt3Wk0bNoa0x9TWF",
	"U0igtLbcW0d7P9Y5jmd2NWQHXKpgTjDVrL+xx0Y9Q4JKY72T8O//61+t3jb7y4yFxYU8gLxMU6PSC8kz",
	"5LK19b1tMz9mJ0Z5WVu5v9+Ya+nWwzVmahW9BAn2vH4zk5K92UjJ0BIDHG0sF2MRk6pXtBuq+swZLyry",
	"OT20/nXIxp5JNZFmR1YpoiOmcSbkGzo8n0o2UEaxe0dAZboJDSuqFWurX916UXAhIp9ymRlb6gchjZbB",
	"YfstFollBaaNzT/aH/33ly+TH788/0uI3jFjPG3N3n4S+Gnhhu+TwmNUGYNCpItfNY+dmZowYpKdr4DB",
	"3q2vjOHKYo0SVQQZ44vfVFymLIKM5/Xf+eK3DKXRffWvAVWBMWdpS97Xc+nOMxr9ILnGJ3n6xrJUd9er",
	"5dE2eYsK7juRVy1yBjbcY9D2trzIQJHaM7427YgTzIZjWAQKM5BYoObSfmF86k1Z3Ortc1J9j+zDe11m",
	"726Bm/Dwki9uvFXm5VIDPBppJmd4QRsvbL77bxxe2DOMkc+NwB08zkYZ1n7F3sT8F21qijqr0fHjsgNt",
	"pnXYPEPa6ETbHWp8nP8sFj+JVS5Ox1Xzn7/HYx6nSNS24h1TLpW+X+J9pgPGxn2mKQrC88WvMRews/f/",
	"foM55jHPMNdi9wAKkSAolKQNmVLWYm0p4pCg4bnSLE2zKlTVHnZivHGRcc0TAXdhz3BXjCk7qM3EOU+M",
	"064wKyTCnlknO3PndGuy3EiM6E+JSj+rF+184EnP/118MCvLRFL7750p5IufBGjM4HUpSf8tH7py5yq3",
	"RRUpOS2pYPlqh8X5aY5m2pOtbarOoS7llFKacY4lyxWLraW1Ac/cuQjLJOzNk+ljkRuK7BkcmEHCGdwl",
	"IkOz9YvfUs0zQR8nArLFL+qA/vHFnjE8zL8hLqUW1rUwYrj1kE8aX+ytnNwQSx1hWqZMrmao5ZT9X0qW",
	"a6Zgjm9RAaOoV4wH0KH4KT8j4oYpzyKYM8kX7+aYQpkx8yioxQd/XV9O1iP5OUtp4wMTO7TK63szP6Eg",
	"Q4WqNy0t3Alsym/qa36GA5GQLkfwPBYk7vGsQGPNhSJcSjOpayJqjunW5NaXN/b2SOu3bKPb5zd2Jt/u",
	"3fjrq/+x9+3kxq1XuwFbqRseaHGX471qLR67eZMZZrbnqFSbvzZQuRc04S7RllrDiApLkaWrbNPgE7AT",
	"Jk+LzwTEIgNWYM4UeOEZQMgxNtup3/wDDVsUKDNmPjNPCOPDFagYpDhjCRvDN8I4LynLFz8z0lsK8IzP",
	"MANzphF4s4igMtkjELERj8b1AKMBG7Y+qEao31OwN+abx6hPRdKb3xhI+WunLJj7u70GUfbekuAcQaMk",
	"tncqcAxP7R+0EFi8rzaozIBpyU9KLfz47IEdM5a8CsFQfiMWJ5L2Q41HK4Jz7TP6J0uFrCI4wkjgMucJ",
	"S9DIjFxIVGM4hExgQuK6kCIxM2I8TxgUEmOuGNkLCU65edJNMOPKTE7aR2lWG+oV343L2Fklo7+abGpH",
	"eQ/fmkw2FvieVF415QuJvjbdtEa8s2rAhqTXD5e0qNKfbcxIoBT8zJokXK82YFZFWa0keaFQDvtilSxs",
	"pP53jLP8P7l/j2OR+dQzKCn7uYW/m/esVvHDXvKhIC5Q0PaFjRxLURvea9xiBeg5xmq5Zzwe8Iw9Wt27",
	"9VVr5l9tLOudm7WWyL/P1OmJYDK5YNDFUfj6kZWaKdS9N0ceq6/lTYfDROe0f5VHPenHz2aCpeo5m2Oy",
	"yTzpqeMV3m/IQjPMv8kT2YD9M/lrkNxRH0sWf7fZYiTGmGtPta8fpWzZA6Etv7MiiGHX196ZqE05/WX1",
	"Ty1wIsF1BSksRPvtNHNPQGWoFJt1RIstMkgQkDLkzKs3WGmHVi8MzuWsEFK7BMJwTmqJwB8ITzeEc0W5",
	"z76jnfIZA6FsRE3B4t8qX9vsGVWm2FSZOAAGPDMLZ4ufjfUwQ8mAJwpysWYQ+toSq96JrApu27MNpEMu",
	"Nw1ySQmLJdmyXrlRgmTT1olC92vl0i/umNc7x0627GMyX8vSh+1c1nD2qqtD6tTKpqN3UyLNEUdLw7uW",
	"au6LuMwwlKY9tJtLPGMsdCHh4YNjuIn0HKD1T+wXT588P4abltXGQLY/Kj/fE/Ae3FGurSbaEiywgyd9",
	"Btj07SEeCoxkt2AzNqp+1djFU56zorhhXxY04UkfbbiEh4KloTnLOq686RubiPTAe3vBwQuM0HtHkEcu",
	"PsSKN89RqnahyN6rlZznjrR5ukUZUUPiA7Q5tHntw+osu6KKYZYmCrgMyZ8PiUq1qamrN7ZyyyLZbLqr",
	"U0GtebflZDPa8LY+avz3ZVHvNdaWNGmUlQmQvMxOUHqn4L2nYPwjDLbuhtmBvHBlNc16oOG98UTEx23N",
	"x+fJrsmSbdJzq8JGKwNDG0g1nyZDdR2d/NU1pZla0xi0bDsbsZTY+triI8nusommUxTBcsqM5G13pJsA",
	"HSauVipstdm9iuIwT+q3dSXQynVeMbm2ck/bTxG1D+5pVbflZRW9PPfqDPbHZ4p62+IdX4syPp6x1uCn",
	"TVT40nqpC4nYzeTolcXRVzPgpcTPN9Pf3/n1kk3QqzX3roT2ys7ao3c2s7WgVdEIWzB0sQq7zYmiU7pY",
	"ljz5o5myfpzoUuzZvyFL9elwYFJppkvVjkuK71bO0z0WGvEf3HYBqAsSRsJsCGotXdMiwE7sPhC8T3nG",
	"dVheiOlUYfC7rlxnFIKxr6qfG9oJ39nbxoasDLAv35emgmOyMlPZ7NgG5feb7d4LhXIr22azi7/r/Xps",
	"MwJr5SAunltYrxh57dqUYGVJcFzMEwqqVJ6gZ1+2CCRNn0xH+9+u61CGXnMeddfzER5fE955dKEOitbz",
	"A/5Xf8NetbbMulAfu2PDbwlt2Ar77ZJN+01s74HdkuI1xssbS4aizp0CWQEZ46oqWHLlh/RRLiiDsUm1",
	"d7DlJeBQUWI0ffNQih9C3s03wmbFEnT1fDAX8eIXiCWqGCmwbxyefapsNZ7P9yXCHLOoSk4q+BeYu2A/",
	"A0OVJyip+6MufJryM6YiKDBlynZLq6ohgF6wU7CZLTXKFz+J3THcr56sqhm5eUnMMjPNqZB1IVBJNfQZ",
	"0CLDhUADqfBqRwacvsdmqaVixmEXdjNsGTPsHB4eHt54/Hg3gvaOEB32awv7Nn5XYq3vQa8l7AI04Ia8",
	"UHR+HWkRGtKyDSaHm8Rg6qe+DtWT3ecM9hoXnAH9nOj3AIQ7B2oi14v3IGDKDcEohfaB14t3gEov3tlc",
	"YrK56z4QwW/Nur/0Lg8GKTB8SEFqCanBYCTUr1avU4OdblPqV7sLwvIwLN5X1eqCGByBqaqcUB34lY3t",
	"h0iAUFWw+7HXh16N7D0cdLJX6vCh4F6o6rCZSUQHb6REVXV/yeH5tTvnlsXxxRxlUmJY8TVB/vZSqbXw",
	"riuYJIlI8pcnbCisuFk8wXqdq5MCzfSX0+bmh3kkMtHoCnHQbrCwPVN0rGN44qiR6ZJ6M1vk6Bgfs1Zx",
	"7poK4+MTEltOJiRrl5FdIIy7sfbpd9C0wqsoY8yrM6OzBMWNGlWgxIlEcIcNO3fgLtz5j7sHVSvPpKYG",
	"X7Qsq99pD02JDrjb7dLZqYkq8qupdw8gFSyHu2BGX7xXmmfCE3ObpU2ItdbMnXj010ukdGJ0y8Nyq0z+",
	"NXly8aGwoXDLcMZuTAQ0vDYV3FaMsE9C2HYlii0TUwlCL5gPO3twt+rUZrvBF3uSOoBrY0xZoN4Cr/eN",
	"usFpnFPxGoN4Jx+Xx23VBzy6eEd++y2XI/stxT2xweM8XksJrEM0QWlCGtERJCnE08U7m7ixLQQhm2/l",
	"3m6QdAhQRZmhdKWHL0dnhgi+eTmKQC0+GHXkeTjkyBhv0FW8iVhIufglj6kxbbX03kai7KPJrEth62bD",
	"kqH2xHBj4sYyrUYfEaB4zlLj0RkR52a0TqrrAjp+SXvjfSdiayHikCTuhroc1yrE3CQj3J7L4n/bEUla",
	"1g5wPSHXfLhW4nh902SjPHAQQ4c6I0mbU2iDWo/qXiILpKVYSjBjuw2eTtNBuVO1UFK/Fem2xFcKV9uY",
	"OFkvKXS16eTl9kTdp3jRtg4uUW3CMFp8h3moFXgmMSEfVFnUNhcgYjJjbzFn0ojaVMzUePCtx/Rpc4L3",
	"kEmUqw05OyX/JZG3svCu6aeMJ4NBcqNYQyK7MzD9LPT+AUF4iZBbn0Cef72U79bKATpl07bNsgqAjv0W",
	"6E+/7473awhqR2WgcuDilQIvKEs94FOuDy/w5YUAOYoifXMsvhZpKn4wO7ES4vAfOGd12Mv4D56NT/F8",
	"L1oGCmclJ8M/EKBRQTXieUI9dXDj1mQdtIxKenSrz2RMuJUJqoz+pu5nL1wUkDYrD2vwhJrgxYbttBvg",
	"NK6Z8fJmfREAi0sErHiScc0lpTkau8kYcTFKLZZhT2xs263Y9WFLLzjHKc+cPq0RXJxDG6qG60720sEV",
	"ljTU2KPutAQvVXwZz/1P96I1O4jHM3YiOaaX1UkMD+371gAr7a/aL1K48mqrS+up3rBsq9963fvpZVZZ",
	"1cBga5dU/RMln77ZDJXNk/JfTPa+utUHI/lYoLZleGf9VRivxAhKrt88j08xc/ltsoUPy5DEODZ2L4iC",
	"xQLECZU4Y+aawZT1D8gAovAxaRhrWNdDn2pdWPxlnk9FwJh6+oii+SLXUqQIU56zPKaK3AKVEixtus0y",
	"kaMmh04BgTcbEcmlaPWhwc6zv8CX4zuTO9GdCdyFL+9M7tyZ7I7hmdDMhmFiliAzK7GQHQLIugfrE5jZ",
	"tNd3AAISkTdJsBoTcvG+ClY3kNaQuPdFgEDdP4qebANfg8U6TxBuT26P4YE0q5gvfsms5v7xZVWO83K0",
	"Dy9H4/H45eg8agONj+GJgocPjlW1gUxF9dxUBDYYs/h58X9RQZGyHF9TQh4DGX0j+jOYc2nh/OJThJ2Y",
	"neDiZ5aeCvivN47MZ/vwt0fHRn08fvT8+e6BcbzT70uUQEdqoa7rFfJ8ziyetnthgilCzuBUSEaeGtfE",
	"G1/z/LAo4PDpI6/Ran80GX8xnpDJbOztgo/2R1+MJ+MvLBPZqMFNv8dwhnogIKxqZF2mnOtYMLP0bAxP",
	"ZGJ3FXhiZmX4mFURMCpHO2yavFoI9bcmk43wytfKv3Txp3sZlz6UebVEzedMmQduT/aGhqkXcLMFu34e",
	"je7Y1Sx/qA1r78sTKiXyJcm3r85fRSNVZhkzjiPtJFnQcWu60UizmTKyq97mV8bOFUoPR/crxFHYqdHP",
	"dz0TRqMk8HFruvcP1UKLVH2mVoKi0vdE8ubSAOg7wOvnbUlNmBs9ctq7/NGHAfDtXsaSE8y9IZo1zt+7",
	"lOFTpbMjyVnTUh6mr/OokRw3f+TJuSW1FENJhyOReUjdUY2Cv3jfSBXYURaMWUFq6HyGuZGziXA4BI1Y",
	"3gUksasMhdNLXo4cTmj1spcjyoG2BiV0JzajoeoH7AcvR7t9Er9Pi/FJfGPBVRsvXg1pd6qj82hNiuzW",
	"qQ5SZLVMUbaH2RZ93p7cXv1Qfa3GFgj6kJKOFdU12wIKAVNG9S9OnQFhzDpKo3gpSy1ufEjGOn3ZJpyH",
	"qD+Kai5XPv2pD/5eqWJPlEXA8zgtFZ+jxxlD+tO78Gegxrf5yc36QiAzgYLpOBQ7UKAlQWyyrKgMcFWe",
	"KM11ufg1EWoMR23p0IkqYMI1CbDbk9sBkWW9+09PK2+f6m2RE3/7Z5d8DxJCRxQZRvZ2CPTMumHN7uo4",
	"h32Cp3VhaVWmnVS1p9/cWLxXdTI0wUJwCoTRiUSWEXPj4ZXJ6pJUcuUUwlSYjwo2E5DTtzTcfnOdQJXz",
	"rR3LSnQr+JemErtVde35c3lVmRIu1vYD08JB0PnFK97UQ7W3sMO0ZMrdjBWnltd3x/AgMz5teSJF5Cq0",
	"7+4ZO2Wyd3Nvj0bJxRyzE1n76WM4rCplYpbGZcpkZAGb/MC6WdKQ62p23Au34xlXGrO+LHmIuqnsH/XE",
	"YQCJt0K6hcW/wVRirtFWCyWtquS6PN4sr0MDOaZIYo1uSjNu8ZvmqrSsSsU2kqLORewNQuiG8NBfXaGA",
	"CnRDBGTUs9rCQI9O/kg+xLOeDdVaqiEH++m01KX0RdG9SvYMO7EPzvgMAc+YJuRWhLK+OUBI/86AMRy7",
	"+m21zu0bB0A4UQTObB5rXVhSS5bq5hLYGby5xI/i7I7hCUng5qKZxXuIRcFZUkvPxlEZQ7N1tfLPPO1v",
	"PsesutFIDfnmIZSmq7EIgrc+bNlbX9rzM8x/1nn/IzKeISrLEu1yb485wjxn1H9S4ZEO6n/DVrzJb2EG",
	"L46PDqCDH0k+t2WzmsAZaSdpMZyVQ3itdbLFlU4sgutPomHsE5bHxE5jeIzmQXv1YCriSsfNudQl4yqo",
	"ymqE1VWa7HGznAgKlkgzDKl3Wiht5lIN1VJQISzRC6X7rlJl9dFngxyjykz4uQXJlJbY5p7tXDxJZ1RD",
	"fnqcuN17L+vrLj22vpY7SjcTD3SOSRfDvT5NYmrjkNoLGioJ0TCQFREOkG9FzmAn4G+r3SgQYdks10JY",
	"9o3BG3Xw6CFDyuTkxvOfCi2M2FPG0M01juGFQqjhT5tkXIXM+KzKK5lRKGlz48jm1vYhFzeUFhKN7s9j",
	"Rk2XlDozPwt45A4/0vaiXxkHd1AqAxRT4VQmxmzywJU+VS1mV8TokgwFhk4q0qzvvfVpUzNHljUYZDAy",
	"VyNs9LVASJ5X2AEBh4N8jLUhDM6j8AAOlCA4wop7QK5UI/SRSAIk9XTxbsZzyiURu21dDTxlZnzrTrRk",
	"8WdtsFlGkY6vtp/C8t+yje+ShZwOQtW8Si/Dv2htyy5GGzEnYJVgKBm4HRJ40MFB/0TY4PbeF9ubwZGQ",
	"hQA8izFB+PI2/J3fs3O4s8050Cg3jt8U2LZQfy8Soc79ZkTOovK/rHRIgec85iyFt9gK2lTiodbBlBO+",
	"yVLjoNV4CmHR0dx/PaCWC0ZulVOaVIPWZntfga4ol7N68wrSIr1LvLecGVklnp63jrFOj2zfe7PwA6IE",
	"ooKO+j5w5MZzVU55zI3B/onIMpva2ZKHi9X9VphTXZ/r1GfQ6ObP8vX3KF8PjZhgbaFqURrI/52i5BIS",
	"np8iHxSwpwRNOOjlPERtwQuv0uXswCOGXE56tYv2c/O7xa9zTO121ftBNcHGiTZ7svgtoSg5ax71tsAt",
	"yu6BddZ9pdIe/aFkc2bzS6KEnJLmRq3VUQbCUXrilRXBjOWnLGtuPgHCdkn5rApKKJsGnFLk8gASppnN",
	"xElu3xhVUQ6bF6SEpfubns1sk2Wd5p+zt7xGO4aES9Si+s6oXuv02qAH3J78NQLmAqYuZ3bKQGKRshjv",
	"Gv2yD2zx6xKf2QVNXeYAELQUMf1ZYFpHRCLIzTCqvVuwUwVMzMxQUopVTdlb0Cw7WbzPgEHKswLfskAc",
	"5FHmxUGWBmCpNZXm1V2ITVVS+pOmS3S8+C3xL7MZiMy6TQp72q7uv9ffc0WWQihYsz0zYY0iMnu7kqPK",
	"RKjtFlD8dYuWCAG5vV68oyuHLZE1UDqGP3LHtYkoW4y2deVbxe8yxglQBOHWBB7f20Yo7pETT2VWh0y7",
	"UcRgKK668e6GRIVaDYvqOt56a3KL5I6oACoE4I2M8bS5F5rSV2N4AvHiQ8Jn1GmIsHcHMp6XNvZ7B+ZO",
	"p1ixfWBmbgR6/YxafIDFe8B8TinYPfewX6viUrxjeI4ZPH98/NSMPOWz0lBG1EzMuyY5FbO+3HP80Op5",
	"uaIASbCvZi3pcmub0uUpEnaavRfpgqLloiTfhJfN0Ru6qEjCmLSQLH6dcU31AHSi9ow96q62GBxJBwn9",
	"JlGKzIYJ/hAUqe5cUAnqrERgUIh08aum/GgN6GVMiMV7sE0gxi6qan9mTGkmwRyYq3M4FFZpSkOc1arq",
	"kmfzIi0SpoDabpUie6ZnGWAeo6RKqUBVgV3VNig5NNQ1edVrEPRzOkuWagvodE0UfUwWE3OUVSonPx0l",
	"bEzDJELfDJPwkSFHT84a2zdGaaurLQ1FlkopmGQo705DrgHyCvQGHlk8r6ugsCWdiJ8egR1Vqs7Pd2+f",
	"wgxXokSg5KknYapprSKxzt1qwbTx4wrrty6pCveTPWtd/XX1LWUBhMY1usr+2c1bf+KdZUIFUu22Xi7q",
	"pty9425Brw7W7DUYffDSIp6+HFlIQawBI3ZqENIK4XC3D7IaEa6ERGUsNotKSMqrNsWYKwZmB/DSB954",
	"OTJysR6MSot7sKwtxMxDr6aWKlQzVwVU/a9gUnPqd51yqfR9i04RkYFeF+3nggoMWSL2zTqMv0HFw1R4",
	"zJR5q6sPZoPVfN7dYVeZXusjV2w5yRZitKEQslcO8oer4nNpmAqxtV5phdRbG3Mr+bEjem/6SDQ3KyyU",
	"wWoJi8MUwJ7Zjty9GJ53qFTAcXGDLvOpnnw9VUKhSZhqA9EY9aiqbgcFX0wg4Rc+fbu7ywlgyQn8TmnA",
	"LJvCiJ8sDRx3ubsDjWSVFJUnIVDIvNWmuwEJVJ27l9/sZlxsbOANYpGd1NU61H7OkwisUQAIDtcJdnLM",
	"T8sM/v1//ivcnkx2x3Bk7I4ODpXxcclKbHCm7D+bnpydsKJ2TrfZsF2KHWV1+HpDeKqIeg3wDLMirQNW",
	"xtdhSvGc6dK8jUK8bAx9+QO2fjArE5ZZ7D2NQw19QdK/IjtgDbixLXtIKxh/kNE/twBaYfK4j2YGeNO4",
	"6dQbWLGQxzsOXre5qGA9wbIKBeBwUJ75eSmmDgjW3EJmpzMzk+qHEWCKPmqAGGrb79jLV9WN6u6SXJ4G",
	"tQE4rxlffG7Gr72wxrTttuVjnZmpYNN9ML4h3/PS9dg/+/xhY6VVM5ZRA9UMd54eHh/9DZbr290xfIPG",
	"364hLJiFvLB6sfY3M5sfXq0VtqQKrl3+b+ISBguc/qz93wnOMSEqtpvWzdoF5boFg7yhO3ciBeN2DgEK",
	"0/YlwDstAEfiFOe57A7G9Qau+t9ChG8YJX0N7+I43L3y6WNJDbXd9MCl6h2CFkkMR/x6+t4Fu16XuRb7",
	"VoraWzDoIhNIMGPGzt6pHTTCFa97hnejoVspyEvAxc/2VoM63Bb1wm0VZlkTcLPN+wolZh2Pm+AAlsTj",
	"+terX3FkbhCddfsxuiWssoQ1fhJ/ZLAsBzLhMIQLVKxhp3XYaFjsXixm17vIZtvhmg2uw1sWrTFs+HuL",
	"1lkokdWRuo+khI3id38Uevjko3dPW0rPkkIAIsb25dsOWd4opN3LpJCrC+9RVIEyXxR58+IFpHHJx8tY",
	"rm1haMI0AyH5jG6OSURTGNtXsM9Rh4jFSLUr0rCd+ya2798s4YzP4a21wls+cL9Pi7U0/kiuEvXtXMNO",
	"0PPFB1tS9i6Ny1T4UefqVl+HEi/SU+bZxpiBYifobmidCk5AVys8pCfejNbBtMgF2NYoAe5+ooNLx7eg",
	"K3muBd9iMx8vcNfaGiroSXPdWI188keyZJ9YbDDacwuEWdp6h6jCGjOC27uj+iN5auN4sVWlK2LF5osI",
	"2q0LPs7skohx2KO79tjxZyDXHpCrf7hhOFc/bryu/L+K8PFzB+/Jobn5BBCqC0ZgR9gLRTqXncDN6mKR",
	"3X0qVMcaJt8r0rJ4R9D2lZqb37MDCLBO1cBEdSTe26jnaUmweVvxjtW30VyXgXaBeMdnI60Vhq6Dz5El",
	"u6gVLnaYn1PjJKyrW6obJobby238zN3Ed6Uxuvq2v2sh0+5dg0sam68JpcJ2EF8fcNeRxASN+cYb+DAX",
	"W/pTN1InOHeXVnUH/AQaqxvdX5oJcHLwmr4V231LPp+72RIShFu36YoU30J9XgkKKzfWSms9Qy1kzjo5",
	"EiGhub8PEowlqhhzjbZIOkGjqZnG6kYUcEhJyuZzjfVMr81sWIRcVJv/Hcj3Gr+vkxD7jF61HL3K3641",
	"Qaz8Q/6TY1mxUll6rqdCbT1nBa9anH5fAFct/m3grYBVIqXVvnI8lN4M2RXbyv9df9rvMrJ926EX18Be",
	"2RnqE+ajz4bHJ2t4bJwA9oMSbaye9QSNMUtKRSp96NYFIaGQfM5iuqo9qiwJyI0H9e6MU0dTIRcfCmMb",
	"VUbSAVhV7aEHvEVCK7dPkxlibQ+gblbjip0ydYpVmbKDQ6quLhjDYXVJUwazVJxYgOlqPEUxbDN1kWue",
	"l8Gom5HML2i169wtYK+mt2tk7bFyBoXV4kNx60u1hAYn15oUg8IefNWxbXHTJKyc7KdsVdF5rWlO1Xtx",
	"DbaUXPyfDCt44SJgWl2/TjCK4PrwxZ6inFawGjXC2O8Lp1Dkqkw1ocvb/YTCLiosa62oWWXNmV9dqRnn",
	"37y8ZfutdQly4DBeVC51r5tym1ZbgnUhVZdZt4gM9MCiu1C3ZQ0IdE32Gt2W+33JlY2cfrbfNg0cHbkT",
	"9ONGAclQm19e1UwwpXPoYvq+6AmYXHRZ8aP77WuKB9IrTu4stYNevHh0vwOA/rtBR+1fO7/l4Pjawu8a",
	"gVEf3acylkoMVjP5bLkED6pju1CpOEpt75Jz3OdDpX5WH5/Vx5UAulbaoAHcxFWaht4v52E5f5idEOwx",
	"pCKmPGgp09H+6FTrYv/mTfrwVCi9/9XkqwlVHrjX9xrXfHQmQwZD+KpOczh41b6Pe9SAkcWV1d1y8OpX",
	"2AX231CnblxwRMgqWdM8W+dn+o//w7/cpbmByBu4FUnpv8DeGNUDM2/j7trKrvqiKda83WLv9l9b3aWD",
	"nat03A1cdFWkGWG++DWnisD6Eqvm3c29OoGNt5foxOXr6i6vxXtghr5ZfsoScVBdZqdExjKo73RXoMoT",
	"LRlmzTj1BZ+hZfSu6tuxiaxUs91V1/a599c3iPXf/6C6fRODd2/uTPkZtdPbKhbzkShh8VvOY0Z3fauy",
	"jXPiRhwoC+iP34NhMsujnSX4IdvMj1khF++VrdVvrhya8jPX4pktflkxm7qFLrTFcdmgnRMuUH7K7G2F",
	"QQTCCpuSMAYqGEI3VBdeK7DjHjgnYAXlWg++BCB454TF35UFIGR85ua761OrZqPzV+f/PwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
