// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3Lj9zGut+/8qFzAswgrVaPLBn2DARkNLJ9lWNZijQ6QGApQA35dU/JJIuqKrZHdmYbZH2XWV3FiwMZ",
	"8ErIxsv0f3L/kqC+KpJFstjNnkdrbMsbt3qarNf3fvzq51Ek0lxkmGk12v95lDPJUtQo6V/PMBIyfvTQ",
	"fI5RRZLnmotstD96FENWpMv3kkcCYgES51xpKUbjETd/z5k+HY1HGUtxtD/i8Wg8kvim4BLj0b6WBY5H",
	"KjrFlJlXz4RMmTa/y/Tnd0fjUcoznhbpaH9vPNJvc7R/wjnK0fn5uXmVykWmkCb5gMXP8E2BSpt/RSLT",
	"mNFHlucJj5iZ8e3Xykz7Z2/Qv0mcjfZH/+F2vQG37V/V7a+kFPKZG8QO2Vz+QxYLBTxbLN8l3HwUhdkC",
	"ySBGyHC+/BBxAQsuEhYz2EkxU2yOKWAKuZC6mBfLX9Xu6Hw8OhLZLOHRFuduR9QCIpGCUBDTWvCMKzM4",
	"KjOrR5lGmbGEXra9qX3NklMG3A5u5vGd0F+LIou3N4Xvlr8IwMwMJlksxuZkc5QaswiBgSi0FFCoYvlO",
	"cmGm+CJjhT4Vkv+EW5zmc1TKzJQVyhzauKJFM0XAs5xLFrORedC90wx5GEWiyPTfud3R5iuZUqhhh2m+",
	"EGPAswmYpTDD3Scsi8QuKJEyyARooVlyAAlnJzzh+i3s5Eyp6rEZ04Wk5yIm9fIX82RxoiXjo/EIM8PX",
	"39vRRuNR9ZLRq4rXlZY8m5vNdRP2+DuXwhwHt7x/ytR/45i41cxYkejR/owlCrsbBswtSGIWI+yo5Qfg",
	"mZU9fCF2J/DUrgKyIovczyajalYnQiTIMjOtH9wGrjpCf6/PS0n48wjPWJon5n3fFScs+8FKu28xm+tT",
	"X96Ve3DuC87v7WvcBOoNEyevMdKNDXOk09mxSCLTGB/qhuCNmcZbmtO7O4fgb3J3L3gcFOFtsX2pTVu9",
	"J6Rd/I3xpjz2Fhzcr/h1ofQ3giUejbE45oZsWPLU2ztHVs3tZKmZ72OeWTG5kSYbj2IuMbIE+nPFGTHm",
	"QnHDGz9yfRpL9mOANVpbUL9o3JhScMkyOuULjPtphLlfdGWE0dxwHzTPThmccqWXH8gCQJgJDky+KfiC",
	"xeIAaLPgvv06Z3MWiwAntVZRjRua9gOeJDybf5Vp+fZRlhcBacAs9TwaSpF2p7qrfM6SWEBcygtMIcJM",
	"s4VQB8BK8bZgHOig+ILBjgDNc++ZmP8EbwosBd/uaLyCNqYBK6e1M9XKqlmv26MVx7vpNtnff+eYsaUv",
	"RYr1sjMGy/e5iFjLJuzIlHrrB0xgoIgJiYXGxnnrGLKNz+z8SX9fqUCNMdGsu5XHRq1CjEpjtXfw7//r",
	"X62+NTvKjGXEhTyArEgSo4pzyVPksrHZnY0yP2YnRulYy7u7w5hp6dbDNaZqnZwOEtp59WYmJXu7kXKg",
	"JQY40VgcxjwlFa1oN1T5nTM61Njn0ND6hxCKPZNyIvWOrFMgR0zjXMi3dHg+lWygRCL3joCqcxPqVzBr",
	"1la9uvGi4EJENuMyNTbQj0Ia7YD9dlckYssKTBtbfbQ/+u8vX8Y/f37+txC9Y8p40pi9/Sbw09wN3yWF",
	"x6hSBrlIlr9pHjnzMmbEJDtfAIO9O18Yg5NFGiWqMaSML39XUZGwMaQ8qz5ny99TlEZnVb8GVDlGnCUN",
	"OV3NpT3P8ehHyTU+yZK3lqXau14uj7bJW1Rw34m8KpHTs+Eegza35UUKitSV8dxpR5woNhzDxqAwBYk5",
	"ai7tH4yHvimLW317TirrkX14r83s7S1wE+5f8sWNrtIsXGk4j0eayTle0DYLm93+G/sX9gwj5AsjcHuP",
	"s1Z/lT+wNzX/jTc1IZ215/hx1YHW0zqsnyFtdKLtDtW+yX8Ry1/EOtek5WL5zz/gEY8SJGpb844Zl0o/",
	"LPAh0wHz4iHTFFPh2fK3iAvY2ft/v8MCs4inmGmxewC5iBEUStKGTClraTYUcUjQ8ExpliRpGfhqDjs1",
	"XrRIueaxgPuwZ7grwoQdVObdgsfG2VaY5hJhz6yTnblzujNdbdyN6aNEpZ9Vi3a+67Tjty4/mJWlIq78",
	"7tYUsuUvAjSm8LqQpP9WD126YaW7ofKEnI1EsGy9o+H8K0czzclWNlXrUFdySiHNOMeSZYpF1tLagGfu",
	"XYRlYvb2yeyxyAxFdgwOTCHmDO4TkaHZ+uXvieapoK9jAenyV3VA//hszxge5t8QFVIL6xIYMdx4yCeN",
	"z/bWTq6PpY4wKRIm1zPUasr+rwXLNFOwwJ9QAaNoVYQH0KL4GT8j4oYZT8ewYJIv3y0wgSJl5lFQyw/+",
	"uj6fDiP5BUto4wMTO7TK642Zn1CQokLVmZYW7gQ25Tf1NT/DnghGmyN4FgkS93iWo7HmQpEppZnUFRHV",
	"x3RneufzW3t7pPUbttHd81s70+/3bn356n/sfT+9defVbsBWarv1De5yvFeuxWM3bzL9zPYclWry1wYq",
	"94Im3BXaUgOMqLAUWbnKJg0+ATth8rT43IbIWY4ZU+CFVQAhw8hsp377LRq2yFGmzHxnnhDGh8tRMUhw",
	"zmI2ge+EcV4Sli3/yUhvUbx9jimYMx2DN4sxlCb7GERkxKNxPcBowJqtD8oRqvfk7K35y2PUpyLuzG8C",
	"pPy1UxbMfW6uQRSdt8S4QNAoie2dCpzAU/uBFgLL9+UGFSkwLflJoYUfVz2wY0aSl6ETypZE4kTSfqjJ",
	"aE1QrXlG/2CJkGXkRRgJXGQ8ZjEamZEJiWoCh5AKjElc51LEZkaMZzGDXGLEFSN7IcYZN0+6CaZcmclJ",
	"+yjNakO94rtxKTsrZfQX003tKO/hO9PpxgLfk8rrpnwh0dekm8aI99YNWJP08HBJgyr92UaMBErOz6xJ",
	"wvV6A2ZddNRKkhcKZb8vVsrCWur/wDjL/rP79yQSqU89vZKymxP4u3nPehXf7yUfCuICBU1f2MixBLXh",
	"vdotVoCeY6xWe8aTHs/Yo9W9O180Zv7FxrLeuVmDRP5Dpk5PBJPxBYMujsKHR1YqplAP3h55rD7Imw6H",
	"ic5p/0qPetqNn80FS9RztsB4k3nSU8drvN+QhWaYf5Mn0h77Z/plkNxRH0sW/bDZYiRGmGlPtQ+PUjbs",
	"gdCW31sTxLDra+7MuEk53WV1Ty1wIsF1BSksRPvN9HBHQKWoFJu3RIstWYgRkDLbzKteWGuHli8MzuUs",
	"F1K7xF1/LmmFwO8JT9eEc005y66jnfA5A6FsRE3B8t9KX9vsGdW52BSXOAAGPDULZ8t/GuthjpIBjxVk",
	"YmAQ+qMlRL0TWRfctmcbSIdcbRrkihIWK7JcneKlGMmmrRJ87tfKpV/cMQ87x1Z+7DK5rlVpv6HZq7YO",
	"qVIrm47eTonURzxeGd61VPNQREWKofTqod1c4hljoQsJ33x1DLeRngO0/on9w9Mnz4/htmW1CZDtj8rP",
	"9wS8B3eUg9VEU4IFdvCkywCbvj3EQ4GR7BZsxkblr2q7eMYzlue37MuCJjzpow2X8I1gSWjOsoorb/rG",
	"OiLd895OcPACI3TeEeSRiw+x5s0LlKpZ4LH3ai3nuSOtn25Qxrgm8R7a7Nu85mG1ll1SRT9LEwVcheTP",
	"+kSl2tTU1RtbuUUebzbd9amgxrybcrIerX9bH9X++6qo94C1xXUaZW0CJCvSE5TeKXjvyRm/hMHW3jA7",
	"kBeuLKdZDdS/N56IuNzWXD5P9pEs2To9ty5stDYwtIFU82kyVNfRyl99pDRTYxq9lm1rI1YSW1dbXJLs",
	"rppoWkURLKPMSNZ0R4x7Yqwr65vEWMZulfmgsUxjmb+UNRTtnGk/PTayZ+st9XVEillcva0ttNZuzTVT",
	"eCNdtf2sUvOsn5alXl4i0kuNr096Xz651NkW7/galHF5XhzAgpto/ZUlVheSypuJ3msLva9nwCsJuW+m",
	"8h0x+cfUmXtbqHuVas3RW5vZWNC6AIatMbpYUd7mRNGqdiwKHv/ZrF8/tHQlJvC/IEv0aX8sU2mmC9UM",
	"ZYof1s7TPRYa8VtuC/7VBQkjZjZqNUjXNAiwFe4PxPsTnnIdlhdiNlMY/FtbrjOK2thXVc/17YTvH25j",
	"Q9bG5FfvS130MV2b3Kx3bINK+81274VCuZVtswnJP/R+PbZJhEFpi4unI4bVLw8uZwkWowTHxSymOEzp",
	"PHr2ZYNAkuTJbLT//VAfNPSa83F7PZdwEuuI0KMLtVk0nu9x2bob9qqxZdbruuyO9b8ltGFr7LcrNu03",
	"sb17dkuK1xit7kXpC1S3amoFpIyrssbJVSzSV5mgpMcmBeLBLpmAQ5W3GWS4wzaIt/qHvFD8eAhxhoa0",
	"p4Tx4SZRguqpr0MVT03HD3PBFVU2oVz+JmyJ02vUg+qeW2TYEzxuTKe7pvDGBk84JCmD8TW/BrpKOLV6",
	"D6kL6j4IWFAJ2PJ9WQMtKKeNYOMbFOg48Ovlmg+JMuxR/tjrSi5H9h4O+mFrxXxfyChUy1bPZAyvl++o",
	"WKes5b7ioO/gfqxV0WGxQBkXGJaNdei4uVRqWLvvyvCo4M4ojhMes77I02Yup3VM1oea6+mvps3ND/NI",
	"pFVLEvXANsr2bScOHesEnjhqZLqgjr8GOQIqvXwHmDZKPicDc9GXDnNvOUQdDy5OukCkb2ON0e3LaAhi",
	"lBFm5ZnRWYLixilVoMSJRHCHDTv34D7c+4+7B2WDyLSiBl+0rKoKaQ5N4XO43+792KmIauzX6O4eQCJY",
	"BvfBjL58rzRPhSfmNgvGE2sNjMh79NcJz7fCOKsjN+uswoE8ufyQ22ipZbg3BctiATWvzQS3dQjsRgjb",
	"DlILFR+p2FBWK947hhRVKiAvEloTNUxUHcLmo/CD+yvFeAACJWdzBlTO7rVb0etpEqfiNQahMS6XOmyk",
	"pB9dvO27+ZarUQyWHJ/Y4GMWDdIQQygqKGpIXTpqJW15unzn7D+qWg/Zemv3doOgdYAqirTKKL0cnRki",
	"+O7laAxq+cHoqrJFiCuiGfImXJGViISUy1+ziHqh1ov2bSRaLk1mbQobmk2J+zriwr1wGwu8CqhCgOIZ",
	"S2CBqZF/bkZDUiUXMABWdNQ9dPK3EiIOvOB+qLFuUO3fJhnF5lyW/9uOSKJ05/Dw8PDW48e71YRcv9ug",
	"xONwu2WjPGIQboWa8UjVU3ccdbtU7SsWc0mxhBCpdmvolbppb6fs2qMWH1J8MdtdiWx0hb1w02FJhetN",
	"R642NqrWuIt2EnCJahOG0eIHzELdp3OJMTmoygJ8ueYkJlP2E2ZMGlGbiLma9L71mL6tT/ABMolyvZVn",
	"p+S/ZOytLLxr+injcW+Q1SjWkMhuDUw/C72/RxBeITrTDcgTD0sZbi2d3KrUtZ19ZbPhxO+6vfmtXryb",
	"g668mJ7M88UzzS8oy9njcA7vaP/8QhgQeZ68PRZfiyQRP5qdWIuG9y0uWBUTM86FZ+NTPNgLpYHCecHJ",
	"8A9Eb1RQjXhuUkcd3LozHQLQUEqPdsGTjAjiMEaV0mdquPViSQFps/awek+ojmxs2MG5AaTfwIyJN+uL",
	"YCZcIUbCk5RrLs0heHaTMeIilFqsgjvY2LZbs+v9ll5wjjOeOn1agYY4hzZUTdWe7JX386/o4bBH3epC",
	"Xan4Up753+6NBzatTubsRHJMrqp5Fb6x7xuAa9ldtZ/kvvZqnStr492w7Kfb7dv56VVW6VRYVINLcv6B",
	"ks/ebgYE5kn5z6Z7X9zp4l9cFhtsFcRWdxXGKzGCkuu3z6NTTF1+lGzhwyIkMY6N3QsiZ5EAcUJVtZi6",
	"/iNl/QMygCi2TBrGGtbV0Kda5xaql2czETCmnj6iUL/ItBQJwoxnLIsosZejUoIldYNTKjLU5NApIJxf",
	"IyK5FI3WJ9h59jf4fHJvem98bwr34fN703v3prsTeCY0s2GYiMXIzEosSoQAsu7B+gRmNs31HYCAWGR1",
	"hqyCIVy+LyPZNfoxxO59Y0CghhNFTzYxksGCdccId6d3J/CVNKtYLH9Nreb++WVZzvFytA8vR5PJ5OXo",
	"fNxEyiZvh2uir695dpjncPj0kdcfsz+aTu5MpmR2Gps156P90WeT6eQzS4jW877tt4bNUfdEXFUFZMqU",
	"c79yZiyMdAJPZGxnBjw2szK8wMooEpUEHda9OQ2Y8jvT6Ubw0IMSHG24305KIwj/TUvUfMEI6/vudK9v",
	"mGoBtxso1+fj0T27mtUPNVHEfZ6kcg6fG79/df5qPFJFmjLjfNFOkhUaNaY7Hmk2V4b/q21+ZWxFoXR/",
	"+LwEioSdCmx61zMDNErCerbmb/dQLSJE2R5opRAq/UDEb68M77uFc33elHYEldAhp72rH30laLxmBOIS",
	"M0s0A87fQ+a/qXR2JDmrO4HD9HU+riXH7Z95fG5JLcFQ4P5IpB4w8rgCHV++r6UK7CiLmqsgMXQ+x0wB",
	"EqYptY9XYlftAgKzElTZl7wcOXjH8mUvR5RkbAxKoDxsTkNVD9gvXo52uyT+kBbjk/jGgqsyALw6vvZU",
	"R+fjgRTZrhXspchymaJoDrMt+rw7vbv+oeoWgy0Q9CEl7kqqq7cFFAImjApMnDoDggZ1lEYxR5ZYmO6Q",
	"jHX6skk436C+FNVcrXz6Sx/8g0JFnigbA8+ipFB8gR5n9OlP79aXnjrL+ie3q1thzARypqOQ/61AS0JG",
	"ZGleGrGqOFGa62L5WyzUBI6a0qHlmWPMNQmwu9O7AZFlPeSbp5W3T/W2ioj/9FeXfF/FBGonUhxbMH70",
	"zLp+ze5qIPt9Aiq8tXlvVyqbhwsyZ5wyrd/dWr5XdZaRuDGLBQhX7kVuT/2S3f0a373MiFZuVymUFfyn",
	"ErfHgqBX+H95wjJ8XbsqRvybXy+cJ8lsbBRlI2wrHCaYX9qhl+8hWb6DHaYlU+6Coyix3Lo7gcOy9iNi",
	"SVQkTI4t6o0fKjbTsJnx5T+X/xcb03tToB9AthcOpV3O/gZ1Xes86ginAJxpCRcKy3+DmbT34XjbTudA",
	"ez8pr6d6UyDF+939VGmZPqw5s4qf7/UijYZgo19do0AIVIAHZMKzSqOjrQwm0v0z2ezPOjZLY6mGkey3",
	"s0IX0mf9ByWv9zuNX53xOQKeMU0AlwhFBbAupA+tPoFjV5CshlxScAAEp0MYtuaxxr0OFb+X5Vuw03vB",
	"g/l9GVvZncATknj1DRzL9xCJnLO4kla1YzCBeusqZZt62tZ8j2l5YYvq84VDYDbXo4GD4Phb9o5X9jn0",
	"8591lv+MjGeIyrJEs37ZY44wzxl1G5ewjb361rAVr3MymMKL46MDaMHskY9r2awicEb6R1qoW+WAMCtN",
	"aeF3Ywt0+YuoGfuEZRGx0wQeo3nQ3qyWiKjUYgsudcG4CiqrCohyna56XC9nDDmLpRmGGhIGaqiGggpB",
	"Ll4oRXWdKqsL0hnkGFWkwo+HS6a0xCb3bOdePTqjChnR48TtXutX3ebnsfVHuYJxM/FA5xi3oa6r0ySm",
	"Ng6gxbEvJUTNQFZEONyyNTH6nYB/q3bHgYjGuNckxYCZTJDftUk7bsF2Q2pExBgy42nPBF2jmSl3d+YE",
	"XiiECiWyTiA5ALuO+HBQebaH9tq4sAXIFzj1EpIvNqZPjSNzYzWRXRGj+wBUfYmpZxo16EszR1oV7l0w",
	"mlUhA3QleUgmlz3PAaeB/ITBrdfn4/AArpk6OMKaKw+uVap3ERQCJPV0+W7OM8q/EMtsXZQ/ZWZ86xI0",
	"5Oknib5ZFo6Or7KBwjLcso3vVoUcBwIQvE5Pwb9TastuQhPpI2BZYCiBth0S+KoF+XxD2ODu3mfbvPZa",
	"5gLwLMIY4fO78Hf+wM7h3lav3jaj3Dp+m2PTyvyjSIQqX5oSOYvSh7LSIQGe8YizBH7CRuClFA+VDqY8",
	"6m2WGCeraswPi476it4etXyxu+bDZVpWb15DKqFzz/CWswnrxNPzxjFWKYXte2C2J14UQFTQUt8Hjtx4",
	"pooZj7gxum+ILLPpkC15qVhe5VPdVM/KcF+pmz/J1z+ifD00YoI1haqFDiAfdoaSS4h5doq8V8CeEqRa",
	"r5fzDWoLunadLmcL1i3kctKrXcSem98tf1tgYrer2g+qReURA7Mny99jinSz+lFvC9yi7B5Yh9tXKs3R",
	"v5FswUAXsaAacUo0G7VWRQp+oeC6V4oDc5adsrS+5AEIcCTh8zKwoGyCbUbRxwOImWY2Xya5feO4jFTY",
	"jBtSss5+pmdT29ynJvB8+aG8pctGVanEnnzcnbvTLyFiSthKUpcH6EQWHqWNyMLVa7RQUGF76mxAgZC9",
	"8MTB4sZCbTc5/uX6h45ENku4rbneqqguoz0p44SJgHBnCo8fbCNwY8mS0WVx4ZiTjaxZql+wnzgLR3LK",
	"u6FuSVSoVT+nPyvLj+9M7zjIBNdXLwBvpYwn9Q2qNOoEnkC0/BDzOTVIIezdg5RnhQ3/3YOFE0mW6w/M",
	"Uow8qJ5Ryw+wfA+YLSgLt+ce9goFyizfBJ5jCs8fHz81I8/4vJAsFuN6Yt6FoomYd5nckWmjVP+a2D3Y",
	"DjCI6e9sk+mfIuFB2RtELsjxF+WBOjppjt7QRUkSxiKCePnbnGtKCdOJ2jP2qLvcYnAkHST025G9p72f",
	"4A9BYXbKDFEy6t1D6Ls3HQ2hLpixYY1aLQs85kxpJsEcmEt1HwrQUkRMGuIsV1VVmZoXaREzBdQtqBSp",
	"Qy8Ya9UbZhFKKmEJJJYDt89fV6RoxUX3N0+LPaezZIm2IDUfiaKPzeEbG4xmUygnPx0lbEzDJELf9pPw",
	"kSFHT84a0ylCaQtaLQ2NLZVSLMJQ3r2aXAPkFWhpOrIYRddBYSsaqG4egR2Vqs5PeW6fwgxXokSg/Jkn",
	"YcpprSOx1i1Ewczh4xLisqqqCbfwPGtcknP9XTwB1LkBjTz/aKcub3gzj1CBbKstmRq3s67ecTfgJHvL",
	"tmrcMXhpURxfjixMGlZ97jsVsGKJ2rbbBY4cUzu8RGUsNou0RsqrMsWYq9JkB/DSxwt4OTJysRrMVXm2",
	"sP0aKICHXuEk3TbvLpNn5f9yJjWnNj3/Pv0xWexVnXQmqMaMxWLfrOP18p2t6qSKUKbMW11BJ+st6PJu",
	"2bnO7Ey34X7LOZoQo/VFIL2KgD9dIZeL4pcolNVKS/TRyphby48t0XvbB9C4XUI49CbbLXxMADJjO3L3",
	"YrjCoUyz4+IaFOOmnnw1VQLPiG2bsIfmAZlQZRm6gs+mEPMLn77d3dUEsOIE/qA0YJaNxpO6sTRw3Obu",
	"FqKLVVJU3YJAEddGZ+QGJFA2S159f5FxsRHeFCx5U9iirZOq2IM6fnk8BmsUAIKDo4GdDLPTIoV//5//",
	"Cnen090JHBm7owWfY3xcshJreBz7z7pZYiesqJ3TbTZsl2JHKWiWnizfp5ui6oyp3BzPMM2TKmBlfB2m",
	"FM+YLszbKPLKJtCVP5AVWcQgLWKWWsgwjX09VEHSvyY7YABK0pY9pDWM38von7qurDB53AVhArxt3HRq",
	"xypZyOMdhwpag68PEyzrGq8Pe+WZq+e2ncLqgKCaLQxwMjczKX84BkzQb9QWfZ3SLXv5uhoA3RVqq7No",
	"NgDn9T+LT/3PlRdWm7btTmgkY1djWkFB+xhifb7nleuxf3T5w8ZKy34cowbKGe48PTw++hdYrW93J/Ad",
	"Gn+7Qg1gFmWgcQ/kgiB7f+JsvVbYkir46PJ/E5cwWB/zV225jXGBMVGx3bR2Yj4o1y2G3a32xdvBuJ0D",
	"3cGkefflTgN3jjjFeS67vXG9nkuxtxDh6wd3HuBdHIcbGG4+fE9f50UHz6faIWiQRH/Er6PvXbDrdZFp",
	"sW+lqEX2p8sZIMaUGTt7p3LQCA65ahvdHXuGfPd+3IOVAPt2BgsuWa1PynFWBN26tw1fc/itFzly+4G4",
	"Ffywgv5/EX9mECLX4u/wTXNUrOaZIbzSL1svFpjr3MCx7ZjMBndvrQrJsPkfLyRngRzWh+MuSQkbBen+",
	"LPRw40N0TxuazZICAXRUKCN1y7DrhOR1mmf3Kink+mJ4FDqg9BaF17ygAPlm5MilLNPL9ynYoBoIyed0",
	"q0Us6uLJroJ9jjpELEaqXZOGbWHhb9+JWcEZn2JYg2JYPqi4T4uVNL4kV4nq5qB+T+f58oOtG3uXREUi",
	"/NAylSJLphyCtUhOmWcAYwqKnSAISg7PBDczFmvcoCfejIZgF2QCbPuMAHd3ysGV4xjQdSEfBcdgM0cu",
	"cA/UABX0pL4KqUK4+DNZsk8syhPtuQUYLGxRw7hEjaKLS5OKmi/JUxsHha0qXRMQNn8w3qDXDNDA71wR",
	"Fg57dB89QPwJILMDkOkfbhgm0w8OD5X/1xEjfu5gEznUtzIAQnn5AewIe9lB6yIGuF1eerC7T9XoWEF4",
	"e5VYFtcGmr6S5RXKHh5AgHXKJhcqFvHeRn0xKyLK24p3rL8p42MZaBeId3wy0hqx5irCPLZkN27EhNH+",
	"b2achKG6pUS/729BtvEzd0vYtcboqpvIPgqZtu9BW9H8+pGQDGyX6ccDaDqSGKMx33gNE+ViS3/pZtsY",
	"F+5CnfaAN6D5ttb9hZkAJwevbk6xHZrk87lb9yBGuHMXTkXTQn1eCgorNwblrp6hFjJjrUSIkFDfLQYx",
	"RhJVVAKXpkbKYZozjeVNE+DQdJRN2hrrmV6b2rAIuag2yduT1DV+X/u6/k8IRysRjvztGgh05B/yXxzv",
	"iBXK0nM1FerdOct52cf0xwJBavBvDYEErBQpjR6V474cZsiu2Fb+7+On/a4i27cdenHN46WdoW4wH30y",
	"PG6s4bFxAtgPSjTxXIYJGmOWFIpUeh+avZCQS75gEV0jPS4tCciMB/XujDtw+uWH3NhGpZF0AFZVe5gB",
	"PyGhUtunyQyxtgdQy6pxxU6ZOsWyFtlB5pSA8hM4LC+/SWGeiBMLJFyOpyiGbaYuMs2zIhh1M5L5Ba12",
	"CEq8vTbbrpE1x8oY5FaL98Wtr9QS6p1cY1IMcnvwZVu2xdaSsHayN9mqovMaaE5Ve/ERbCm5/D8pljCy",
	"ecC0+vg6wSiCj4dB9RTlrMTOqFCo/lhYdiJTRaIJRdzuJ+R2UWFZa0XNOmvO/OpazTj/Vtgt22+NC1oD",
	"h/GidKk7LZPbtNpirAqp2sz65RYxNy2EC7VU2irBcke2b6/RTZ5vCq5s5PST/bZp4OjInaAfNwpIhsr8",
	"8qpmgimdQxfT90VPwOSii1QfPWxeodqTXnFyZ6Ud9OLFo4ctkOw/DIJm90rsLQfHBwu/jwie+eghlbGU",
	"YrCcySfLJXhQLduF6sFRaswiBOa4z4fT/KQ+PqmPawH9LLVBfZEBrtM09H65CMv5w/SEoHEhERHlQQuZ",
	"uBvK92/fpi9PhdL7X0y/mFLlgXt9pzvNh2AyZNCHwek0h4Pg7Pq4RzXiWFRa3Q0Hr3qFXWD3DVXqxgVH",
	"hCyTNfWzVX6m+/i3/iUe9U0z3sCNSEr3BfZmoA7gdROb1VZ2VRcKsfrtFp+1+9ryzhRsXZniblqii/rM",
	"CIvlbxlVBFaXFdXvru9PCWy8vSwlKl6XdzYt3wMz9M2yUxaLg/LSMiVSlkJ1V7YCVZxoyTCtx6kuTgwt",
	"o3Ml245NZCWa7a67ns29v7opqvv+r8q7DzF48+HOjJ9Rz7ytYjFfiQKWv2c8YnSHsiqaYCZuxJ6ygO74",
	"Hawld6+jshhDtmMf01wu3ytbq19fLTPjZ66PM13+umY2VZ9caIujokbEJvCf7JTZW+mCMIMlACUBCZRY",
	"g26oNoZWYMd9SE4sYVSrwfsvXoGdExb9UOSAkPK5m++uT62ajc5fnf//AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
