// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3Lj9zG1t+/ctC5AWYQqtUjS4bvDARkLNm+yr2yFM3oIoGlADXk6Z6SSRZVVWyP5Mw2yPpbZvU5Xlzo",
	"Al4J2XiZ/k++v+RDnSqSRbLYj3n0jG1541F3k/U6dd7nd34cxSIrRI65VqP9H0cFkyxDjZL+9QJjIZMn",
	"j83fCapY8kJzkY/2R08SyMts8UHyWEAiQOKMKy3FKBpx833B9OkoGuUsw9H+iCejaCTxbcklJqN9LUuM",
	"Rio+xYyZV0+FzJg2v8v15/dH0SjjOc/KbLS/F430uwLtVzhDOTo/PzevUoXIFdIkv2TJC3xbotLmX7HI",
	"Neb0JyuKlMfMzPjuG2Wm/aM36J8kTkf7o/9wt9mAu/ZbdfcrKYV84QaxQ7aX/5glQgHP54ufUm7+FKXZ",
	"AskgQchxtvgYcwFzLlKWMNjJMFdshhlgBoWQupyVi3+q3dF5NHqSa5Q5S2nI7S3ga5aeMuB2cDOPb4X+",
	"WpR5sr0pfLv4WQDmZjDJEhGZPSxQasxjBAai1FJAqcrFT5ILM8WXOSv1qZD8PW5xmkeolJkpKxXmGqP6",
	"1M0UAc8KLlnCRuZB904z5GEcizLXf+V2R9uvZEqhhh2m+VxEgGdjMEth5h6dsDwWu6BExiAXoIVm6QGk",
	"nJ3wlOt3sFMwperHpkyXkp6LmdSLn82T5YmWjI+iEebmBn1nRxtFo/olo9f1rVJa8nxmNtdN2LtJhRTm",
	"OLi9ZadM/XeOqVvNlJWpHu1PWaqwv2HA3IIk5gnCjlp8BJ7bW87nYncMz+0qIC/z2P1sPKpndSJEiiw3",
	"0/rebeCyI/T3+rziOT+O8IxlRWre9215wvLvLV/5G+YzfepzlmoPzn0W9Z19jZtAs2Hi5A3GurVhjnR6",
	"OxZLZBqTQ91icQnTeEdzenfvEPxN7u8FT4LMsssgL7Vpy/eE+Li/Md6UI2/Bwf1K3pRKfyNY6tEYSxJu",
	"yIalz729c2TV3k6Wmfk+5bllkxvJjGiUcImxJdAf65uRYCEUN3fjB65PE8l+CFyNzhY0L4paUwouWcan",
	"fI7JMI0w94s+jzAyEh6C5vkpg1Ou9OIjyVqEqeDA5NuSz1kiDoA2Cx7ajws2Y4kI3KTOKupxQ9P+kqcp",
	"z2df5Vq+e5IXZYAbMEs9T9alSLtT/VUesTQRkFT8AjOIMddsLtQBsIq9zRkHOig+Z7AjQPPCeybh7+Ft",
	"iRXj2x1FS2hjEtAnOjtTr6ye9ao9WnK8m25TW2pscH/dk9+6a9yRtCLDZsNyBosPhYhZR2/rcaPm0NaY",
	"+prMKcRQWlvuraO9H+scxwu7GtIDrpQxJ5hq1t/YYyOeIUGlsd5J+Lf//S9Wbpv9ZUbD4kIeQF6mqRHp",
	"heQZctna+t62mR+zEyO8rK7c32/MtXTr4RoztYpeggR7Xr+ZScnebSRkaImBG200F6MRk6hXtBuq+swp",
	"Lyryb3po/euQjT2TaiLNjqwSRI+YxpmQ7+jwfCrZQBjF7h0BkekmNCyoVqytfnXrRcGFiHzKZWZ0qR+E",
	"NFIGh/W3WCT2KjBtdP7R/uh/vHqV/Pj5+Z9C9I4Z42lr9vaTwE8LN3yfFJ6iyhgUIl38onns1NSE0SXZ",
	"+QIY7N37wiiuLNYoUUWQMb74VcVlyiLIeF7/nS9+zVAa2Vf/GlAVGHOWtvh9PZfuPKPRD5JrfJan7+yV",
	"6u56tTzaJm9RwX0n8qpZzsCGexe0vS0vM1Ak9oytTTviGLO5MSwChRlILFBzab8wNvWmV9zK7XMSfU/s",
	"w3vdy97dAjfh4SVfXHmr1MulCng00kzO8II6Xlh99984vLAXGCOfG4Y7eJyNMKztir2J+S/aVBV1WqO7",
	"j8sOtJnWYfMMSaMTbXeosXH+i1j8LFaZOB1TzX/+Sx7zOEWithXvmHKp9OMSHzMdUDYeM01eEJ4vfom5",
	"gJ29//8rzDGPeYa5FrsHUIgEQaEkaciUshprSxCHGA3PlWZpmlWuqvawE2ONi4xrngh4CHvmdsWYsoNa",
	"TZzzxBjtCrNCIuyZdbIzd073JsuVxIj+lKj0i3rRzgae9OzfxUezskwktf3emUK++FmAxgzelJLk3/Kh",
	"K3OuMltUkZLRkgqWrzZYnJ3maKY92Vqn6hzq0ptSSjPOsWS5YrHVtDa4Mw8ucmUS9u7Z9KnIDUX2FA7M",
	"IOEMHhKRodn6xa+p5pmgjxMB2eKf6oD+8dmeUTzMvyEupRbWtDBsuPWQTxqf7a2c3NCVeoRpmTK5+kIt",
	"p+z/WrJcMwVzfI8KGHm9YjyADsVP+RkRN0x5FsGcSb74aY4plBkzj4JafPTX9flkPZKfs5Q2PjCxQyu8",
	"3pr5CQUZKlS9aWnhTmDT+6a+5mc44Anp3giex4LYPZ4VaLS5kIdLaSZ1TUTNMd2b3Pv8zt4eSf2WbnT/",
	"/M7O5Lu9O39+/T/3vpvcufd6N6Ardd0Drdvl7l61Fu+6eZMZvmxHqFT7fm0gci+owl2hLrWGEhXmIktX",
	"2abBZ2AnTJYWnwmIRQaswJwp8NwzgJBjbLZTv/sbmmtRoMyY+cw8IYwNV6BikOKMJWwM3wpjvKQsX/yD",
	"kdxSgGd8hhmYM43Am0UElcoegYgNezSmBxgJ2Fzrg2qE+j0Fe2e+eYr6VCS9+Y2BhL92woK5v9trEGXv",
	"LQnOETRKuvZOBI7huf2DFgKLD9UGlRkwLflJqYXvnz2wY8aSVy4Yim/E4kTSfqjxaIVzrn1Gf2epkJUH",
	"RxgOXOY8YQkanpELiWoMh5AJTIhdF1IkZkaM5wmDQmLMFSN9IcEpN0+6CWZcmclJ+yjNakO54ptxGTur",
	"ePQXk031KO/he5PJxgzf48qrpnwh1temm9aID1YN2JD0+u6SFlX6s40ZMZSCn1mVhOvVCswqL6vlJC8V",
	"ymFbrOKFDdf/nnGW/2f373EsMp96BjllP7bwV/Oe1SJ+2Eo+FHQLFLRtYcPHUtTm7jVmsQL0DGO13DIe",
	"D1jGHq3u3fuiNfMvNub1zsxai+U/Zur0RDCZXNDp4ih8fc9KfSnUl+8eeVd9LWs67CY6p/2rLOpJ3382",
	"EyxVR2yOySbzpKeOV1i/IQ3NXP5NnsgG9J/Jn4PkjvpYsvj7zRYjMcZce6J9fS9lSx8IbfmDFU4Mu772",
	"zkRtyukvq39qgRMJritIYSHab4eZewwqQ6XYrMNabJJBgoAUIWdevsFKPbR6YXAuZ4WQ2gUQhmNSSxj+",
	"gHu6IZxrin32De2UzxgIZT1qChb/WtnaZs8oM8WGysQBMOCZWThb/MNoDzOUDHiiIBdrOqFvLLDqncgq",
	"57Y920A45GrDIFcUsFgSLeulGyVIOm0dKHS/Vi784o55vXPsRMsuE/laFj5sx7KGo1ddGVKHVjYdvRsS",
	"aY44WuretVTzWMRlhqEw7aHdXLozRkMXEr756hjuIj0HaO0T+8XzZ0fHcNdetTGQ7o/Kj/cErAd3lGuL",
	"iTYHC+zgSf8CbPr20B0KjGS3YLNrVP2q0YunPGdFcce+LKjCkzzacAnfCJaG5ixrv/Kmb2w80gPv7TkH",
	"LzBC7x2hsRSb83ymaImGhNL02XS0/93yIY68h85fd30JL1ChnDOgbL3URWxtNMZ+sYPEeOxlUM7joHZ7",
	"7K+OZKhQUEwzdVBlk4Xet264x+6XVVGCXOTih7Bi7+coVTuVZu/1St7kiL55unV3ooYJDNzeIfJqk3Nn",
	"2dW9GWZ6FQFdWjbmQ8JEbWoM6I3tgLJINpvu6mBZa95tSdKMNrytTxoPx7K4wBprS5pA08oQUV5mJyi9",
	"U/DeUzB+CZW2u2F2IM+hW02zHmh4bzwmermtuXwk8YZ0/SaAucqxttJ1tgFX82kylPnSifDdUCCuNY1B",
	"3b+zEUuJrS9PL0l2V000HQlp5GAiIG8bbN0Q8TBxtYKFqw2TVRSHeVK/rcuBVq7zmsm1FZ3bfhCtfXDP",
	"q8w2L+7qZQKsjvFfPpbW2xbv+FqUcfmL5RSvTaxY3rFiKdix+FhI7rkpSOt86FKEKkPuAvb2Rlf6Qjyc",
	"JSnP1xTMa3lB8pal7A3RzhFdxwOyBrfbRMFamu93oc3bTMpdWxxoNR1dSfxnM+3qez/ft3HatubelZ9e",
	"2mR79M5mtha0ipZswtvFMkQ3J4pO6m1Z8uT3Zmj4fs4rsTb+gizVp8OOdaWZLlXbry6+XzlP91hoxL9x",
	"W8WiLkgYCbMu1LU0gRYBdmJPgeBTyjOuw/xCTKcKg991pS4jF6J9Vf3c0E74pvg2NmRlgGj5vjQZSJOV",
	"kfZmxzYoH9ls914qlFvZNhsd/03v11Mb0Vorhnbx2Nh6yfRr51YFM6OC42KekMurstM97b9FIGv5OZe/",
	"5jzqrucS9njjfHtyoQqg1vMD1nF/w163tswauJfdseG3hDZshf52xYbXJpbRwG5J8Qbj5YVRQ1GTToK3",
	"gIzxyl1dpc/SR7mgCNwm1QrBkq2AuUuB/fTdN1L8ELI9H0lULsOcolDG9tynNGxjhL4tEeaYRVUkXVG2",
	"rC1OqvPy6KMICkyZssX8qqpXoUd2CjazmXD54mexO4ajxUcQtvYQbcUGNumu+2Ad0Yt/LP4fqjoflytA",
	"mLugGAND/ScoYcpjloFafIScQWGOinweY6Ai+aykGpEMaBPCiW4DqR7Vjg2Y7E/N7pSKJcLsVRzYRNg5",
	"PDw8vPP06W4E7d0kgu0n0faNgS5rW98RshZXDBCLG/JCYah12EpoSHu/MDncxO6un/o6lDj5mDPYazwp",
	"PmUcOMqzOe9MLz6AgCnPDDkrtA+8WfwEqPTiJ+tuSDb3wAwEYlqz7i+9e1mDpBg+pCC1hORl0KHtl2XU",
	"MfBOWTUVZj4EYS8hLD5UZRmCmAMCU1XerDrwU3jbDwlI0Ka/ux97gAvVyN7DQWt8pbAf8tGG0mubmUR0",
	"8IZdVOUlVxxlWbtEdFk4RsxRJiWGJWQTq2kv1fnGbGYw5QATA+UJG/IOb+Z4sObp6thOM/3ltLn5YT4S",
	"mWikjjhoVxLZ4kA61jE8c9TIdElFyC1ydBcfs1YW+pqS4/JxpS3HhJK18yUv4I3fWPr0S8VaXnKUMebV",
	"mdFZguJGjCpQ4kQiuMOGnQfwEB78x92DqmZtUlODz1qWJaq1h6Z4FTzslqPt1EQV+WUDuweQCpbDQzCj",
	"Lz4ozTPhsbnNol90tdYMgXn014uHdZx5y/13q2yDNe/k4mNhIxr2wr0tWZ4IaO7aVHCbGsVuBbPtchSb",
	"D6kShF5MBnb24GEFScB2gy/2OHUAwMkoxUBFNF6RJ8Ee0Din4g0GgX0uF45vpXk8uTj0RPstV8P7LcU9",
	"s17mPF5LCKxDNEFuQhLRESQJxNPFTzb+ZmtlQjrfyr3dIDoRoIoyQ+lybF+NzgwRfPtqFJFxg5lvCJFF",
	"Y8xGFxQTsZBy8c88pgrM1dx7G/HOS5NZl8LWDWomQ3W44QrcjXlaDbMjQPGcpcaiMyzOzeiaYoZL6ngf",
	"OxZbM5E6FBoo510rArpJYL89l8X/sSO2DeAmNmurbNeK/6+vmmwUzg+CRVEJMElzqsmlGru6aM4iximW",
	"Ep7ebgMc1ZQK71S1wlRYSLIt8YXC9VbgTtaLHl1vVsByfeKonXS63lV7VkKZOdVhys8a18pKFBzf376a",
	"3AurWAY0TkFfEABlMuTlWekZ220VcHfDAaum1znJaq5L0+Lr8ueLVotxiWoT9qTF95iHEAZmEhOy+JUF",
	"g3QFqExm7D3mTJqDTMVMjQffekyfNvflS2QS5Wq12U7Jf0nkrSy8a/o548lg7MKoMSEB2T0h87PQ+23e",
	"yzDmw3D6S6WJutyWtyUCgww1A2bMLpafMsdiRVknSF9pJkwAWIHmIUGj3Og6hqRNkw/TzYti70UtRu48",
	"fry7DtzJJVNmlh3dxeDqfmMpR+sbThtXaF0uQWlAb7tCKMxbkL+0XirL1tKcOuVMFv6gkm9jX7Ld/np4",
	"3s+Nqv0qAxlRF8+AeknZNwMusPVhfz6/EFBWUaTvjsXXIk3FD2YnVkIP/w3nrPbSI/jWhI1Tes59UDgr",
	"OfkpAv5kFdR6PcdNT3u9c2+yDluvxG8351nGhCedoMrob0Il8bzbAXG98rAGT6jxtW4Ic7EBfvKakXxv",
	"1hcBlrpCIKlnGddcUny3MfOMzRmj1GIZJtTGpuiKXR82TINznPLMKaQ1sprzv4VysLuTvXLQoyUavT3q",
	"DlTHUsGX8dz/dC9aE9ljPGMnkmN6VQgf8I193xog4v1V+8lX155FemVYJxumo/YhUXo/vcrs0Rqwc+1U",
	"0b+j5NN3m6Glelz+s8neF/f6IGGXBVBdhkPaX8V5NFKGUXL97ig+xczl7ZAxeViGOMaxMRxBFCwWIE6o",
	"sAYzV6StrIFNChBFu0jCWMu0HvpU68L2ReD5VASUqedPKPgoci1FijDlOctjqgMpUCnB0qYKPBM5avI/",
	"KaCmCoZFcila9eGw8+JP8Pn4weRB9GACD+HzB5MHDya7Y3ghNLNe45gZzVtUUFrGOjSrtEa1mU17fQcg",
	"IBF5E7OvsZoXH6rYWtNqAhL3vggQqOZU0ZPthhRge5AkCPcn98fwlTSrmC/+mVnJ/eOrKs3w1WgfXo3G",
	"4/Gr0XnUbgAyhmcKvvnqWFUbyFRUz01F7QyiImU5viEXTSiDyLD+DOZcWpjd+BRhJ2YnuPgHS08F/Lc7",
	"j8xn+/CXJ8dGfDx9cnS0ewBvS5aS/UtHaktS6hXyfM5snwv3wgRThJzBqZCMXB1c0934mueHRQGHz594",
	"5b37o8n4s/GEVGajbxd8tD/6bDwZf2YvkXVy3vVr/109TcBroGrEe6ac76VgZunZGJ7JxO4q8MTMytxj",
	"VjnsKc32sCktbnWOuTeZbNRHZK1wcbcvRC9A3G8xUi1R8zlT5oH7k72hYeoF3G21QzmPRg/sapY/1G43",
	"4/MTSpH0Ocl3r89fRyNVZhkzhiPtJGnQcWu60UizmTK8q97m10bPFUovcQE5JHDYqbuS7HoqjEZJTUGs",
	"6t4/VAv5VeE/WA6KSn8pkndX1him0xDlvM2pXZl/h5z2rn704cY0di9jyan9jCGaNc7fa5Z0W+nskeSs",
	"KZIL09d51HCOuz/y5NySWoqhGOkjkXkdNKK6O83iQ8NVYEfZJgkKUkPnM8wNn02Ewwdq2PIuILFdZSic",
	"XvJq5PC7q5e9GlHKRmtQQl1kMxqqfsB+8Gq02yfxx7QYn8Q3Zly18uLlxnenOjqP1qTIbv79IEVWyxRl",
	"e5ht0ef9yf3VD9XtrrZA0IeUI1FRXbMtoBAwZZSu58QZENqIo7TaVT7EY528bBPON6gvRTVXy5/+0Af/",
	"Zalij5VFwPM4LRWfo3czhuSn14hvoHah+cndulGfmUDBdBzyHSjQkqCvWVZUCrgqT5Tmulz8kgg1hkdt",
	"7tDxKmDCNTGw+5P7AZZlrfvbJ5W3T/U2J5O//6Nzvq8SQi0WGUa2axN6at2wZHdp58M2wfM6D74qP0mq",
	"VPlv7yw+qDp3I8FCcHKE0YlE9iLmxsIrk9UZ9GTKKYSpMB8VbCYgp29puP2mzU+VolIblhXrVvCfmqKT",
	"VlDds+fyKpHO/Lpv2vmOaeGgYf1cO2/qoVIB2GFaMuU6Vsapveu7Y/gqMzZteSJF5CpLHu4ZPWWyd3dv",
	"j0bJxRyzE1nb6WM4rBL7YpbGZcpkZIEUfce6WdKQ6UpB38bdjmdcacz6vOQb1E3F0qjHDkOBXIdAD4t/",
	"hamk2DElNyatIoq6Esgsr0MDOaZIbI06mBqz+F3TwjSrMkcaTlHHIvYGoe1DfUpeXyODClR5BXjUi1rD",
	"QI9Ofk82xIueDtVaqiEH++m01KX0WdGXFe8ZNmK/OuMzBDxjmhDVEcq6o4+Qfi+fMRy7chO1TlesAyD8",
	"RmqaYB5rNRKrOUvVUQx2BjuK+V6c3TE8Iw7cNIBbfIBYFJwlNfdsDJUxNFtXC//Mk/7mc8yqToNqyDYP",
	"oSdej0YQ7Ma0ZWt9aS3j8P2zxvvv8eIZorJXol2d4l2O8J0z4j+pcMIH5b+5VryJb2EGL48fHUAH15ls",
	"bnvNagJnJJ2k7a2gHPJ6LZNtv4fEIqv/LJqLfcLymK7TGAjA0SrPLBVxXeDJpS4ZV0FRViOfr5JkT5vl",
	"RFCwRJphSLzTQmkzl0qoloAKYXxfKNx3nSKrjwofvDGqzIQfW5BMaYnt27OdhtB0RjUUt3cTt9uPum5D",
	"7V3rG+kdvhl7oHNMur1V6tOkS20MUts4qeIQzQWyLMIB5a6IGewE7G21GwU8LJvFWqjHTKPwRp0+MZTT",
	"aFiIsfynQgvD9pRRdHONY3ipEGq8ryYYVyEmv6jiSmYUCtrceWRja/uQiztKC4lG9ucxo7JxCp2ZnwUs",
	"cofrbDE2ru0Gd9CjAxRT4UcnRm3yIP1uqxSzK2JUza/A0ElFmnU/ep82NXNkWYM0Bz1zNXJQXwqE+HmF",
	"iRIwOMjGWBua5TwKD+DAVoIjrOjPda0SoY+wFCCp54ufZjynWBJdt62LgefMjG/NiRYv/iQNNoso0vHV",
	"+lOY/9tr45tkIaOD6jKu08rwG6Bu2cRoI4EFtBIMBQO3QwJfdfqT3JJrcH/vs+3N4JGQhQA8izFB+Pw+",
	"/JV/aefwYJtzoFHuHL8rsK2h/lY4Qh37pbIQowFZ+8tyhxR4zmPOUniPLadNxR5qGUwx4bssNQZaDf8S",
	"Zh2HyZvSypsBsVwwMquc0KQctPa19wXoinQ5KzevISxSL+KGIiOr2NNR6xjr8Mj2rTeLliJKICroiO8D",
	"R248V+WUx9wo7LeEl9nQzpYsXKz6TmJOeX0OWIRBI5s/8dffIn89NGyCtZmqBZUh+3eKkktIeH6KfJDB",
	"nhLk6qCV8w1qC8p6nSZnB/Y1ZHLSq523n5vfLX6ZY2q3q94Pygk2RrTZk8WvCXnJWfOotwVuUXYPrLHu",
	"C5X26N9INmc2viRKyClobsRa7WUgALlnXloRzFh+yrKmIxkQFFXKZ5VTQtkw4JQ8lweQMM1sJE5y+8ao",
	"8nLYuCAFLN3f9Gxma8LrMP+cvec1xj4kXKIW1XdG9Fqj1zo94P7kzxGVa+aiiqLlpwwkFimL8aGRL/vA",
	"Fr8ssZmd09RFDgBBSxHTnwWmtUckgtwMo9q7BTuVw8TMDCWFWNWUvQfNspPFhwwYpDwr8D0L+EGeZJ4f",
	"ZKkDlirpaV7dhdhQJYU/abpEx4tfE7/J3IBn1m1S2NJ2ef+9+p5r0hRCzprtqQlrJJHZroeOKhOhtptA",
	"8ectaiIiXvyTkr80VpetQf4y9yN3tzYRZeuibV34Vv67jHHCP0K4N4GnX27DFffEsaeybpTV8yIGXXFV",
	"J9o7EpVrxBVm1bW/9d7kHvEdUeHpCMA7GeOpPQdzSBS+GsMziBcfEz6jSkOEvQeQ8by0vt8HMHcyxbLt",
	"AzNzw9DrZ9TiIyw+AOZzCsHuuYf9XBUX4h3DEWZw9PT4uRl5ymeloYyomdic8UovS8Wsz/fcfWjVvFyT",
	"gyRYV7MWd7m3Te7yHAnq0fYrvCBruSjJN+5lc/SGLiqSMCotJItfZlxTPgCdqD1jj7qrLQZH0kFCv0uU",
	"IrNhgj8ERaI7F5SCOiMYhkKki180xUdr/EGjQiw+gC0CMXpRlfszY0ozCebAXJ7DobBCUxrirFZVpzyb",
	"F2mRMAVUdqsU6TM9zQDzGCVlSgWyCuyqtkHJoaFuyKpeg6CP6CxZqi3+3A1R9DFpTMxRVqkc/3SUsDEN",
	"Ewt9N0zCjww5enzW6L4xSptdbWkoslRKziRDeQ8acg2QV6A28JGFH7wOCltSiXj7COxRJer8ePf2Kczc",
	"SpQEtd3iMNW0VpFYp+dpMGz8tMIwr1OqwvVkL1oNJ6+/pCwAKLtGVdnfu3HrW15ZJlQg1G7z5aJuyN07",
	"7hZS9GDOXgMpCq8sQPOrkUVAxRowYqfGTK4AWXf7mNAR4UpIVEZjsyCqJLxqVYy5ZGB2AK984I1XI8MX",
	"68EotbiHIt0C+D30cmopQzVzWUDV/womNad61ymXSj+26BQRKeh10n4uKMGQJWLfrMPYG5Q8TInHTJm3",
	"uvxgNpjN53WsvM7wWh+5YstBttBFG3Ihe+kgv7ssPheGqQCm65VWwOK1MrfyPnZY710fieZuhYUymC1h",
	"gcwC2DPb4bsXaz8QShVwt7hBl7mtJ19PlVBoEqbaQDRGPKqq2kHBZxNI+IVP3+7ucgJYcgK/URowyyY3",
	"4q2lgePu7e5AI1khRelJCOQyb5XpbkACVeXu1Re7GRMbG3iDWGQndbYOlZ/zJAKrFACCw3WCnRzz0zKD",
	"f/tf/wL3J5PdMTwyekcHh8rYuKQlNjhT9p9NTc5OWFA7o9ts2C75jrLafb0hPFVEtQZ4hlmR1g4rY+sw",
	"pXjOdGneRi5eNoY+/wGbP5iVCcsseKXGoYK+IOlfkx6wBtzYli2kFRd/8KJ/KgG0zORpH80M8K4x06k2",
	"sLpC3t1xaOBNX5X1GMsqFIDDQX7mx6WYOqAuDBbhP52ZmVQ/jABT9FEDxFDZfkdfvq5qVNfBeHkY1Drg",
	"vGJ88akYv7bCGtW2W5aPdWSm6vLgg/EN2Z5XLsf+3r8f1ldaFWMZMVDNcOf54fGjv8Byebs7hm/R2Ns1",
	"hAWzkBdWLtb2Zmbjw6ulwpZEwY3z/01MwmCC0x+1/jvBOSZExXbTulG7IF+3YJB3dKeFW9Bv5xCgMG23",
	"nt9pATjSTXGWy+6gX6+HQbk1D99wU4c1rIvjcPXK7ceSGiq76YFL1TsELZIY9vj15L1zdr0pcy32LRe1",
	"TXuo7xIkmDGjZ+/UBhq1QahrhnejoSY6ZCXg4h+2CUvtbot67rYKs6xxuNnifYUSs47FTXAAS/xxPXK5",
	"bs/cIDrr9n10S67Kkqvxs/g9g2U5kAmHIVygYs11WucaDbPdi/nsen23tu2u2aB75zJvjbmGvzVvnYUS",
	"We2puyQlbOS/+73Qw6333j1vCT1LCgGIGFuXbytkeSOQdq+SQq7PvUdeBYp8kefN8xeQxCUbL2O5tomh",
	"CdMMhOQzanSViCYxti9gj1CHiMVwtWuSsJ2GLdu3b5bcjE/urbXcWz5wv0+LNTe+5K0SdTPBYSPoaPHR",
	"ppT9lMZlKnyvc9XO3KHEi/SUeboxZqDYCbqG0lPBCehqhYX0zJvROpgWuQBbGiXA9cE5uHJ8C+ogdiP4",
	"FpvZeIHWkGuIoGdNd8Qa+eT3pMk+s9hgtOcWCLPMXJs0hzVmGLfXnP+Sd2pjf7EVpSt8xeaLCNqlCz7O",
	"7BKPcdiiu3Hf8Scg1x6Qq3+4YThX32+8Lv+/DvfxkYP35NB0PgGEqsEI7AjbUKTT7ATuVo1FdvcpUR1r",
	"mHwvScviHUHbVnJFC2XCsgMIXJ2qgInySLy3Uc3TEmfztvwdq7vR3JSCdgF/xyclreWGrp3PkSW7qOUu",
	"dpifU2MkrCtblG0IemfmOoKG3dNGXvMadzcvU6HcjZOoUM5ZEDTMbzZ6jfTlDxNG3jIztKR0i2Hn7Cwz",
	"zJUxa9/a1o6zksmEybrNqW/dunUDHR1x33JF79SdPWCwN5nsDnZRFWW4z2uZga2F5LbnB5GDpQOJmZhj",
	"ZiHliRbgEA6fP6EyITt/EJAvfs1Qin3oLAyrD0gPsUkkrjqDuG2tOSnIGWhMA6R2xObYpbVrsHK7ZLY9",
	"DromhSuWzn9XvuHHOOU5AhUPGiJraMzdk+HbQLzNdc8Zhs6wsQHXpvda4w91K+AbEcHdRsRLQBtuCIHH",
	"oiPcHCjhI4kJGtOUN9CIzm/+hwaJSHDuGvJ1B7wFoBGNXVOaCXByXjU1eRZZgPxZru01JAj37lP7J9/6",
	"PqoYheUbmroML4fBO3a/2YbfpdP1eA1Xy9MGUO4WsvWjkoBrCWKSch4Kyd77+RTV5g7HxqusInoSxInk",
	"M0b4uELZmuO6m3FUtegmp6Hwm3GHcO8PbKFO83T1RMLeltYjSo0wqEJFYswVo+uhShbZmD9libiHdqY2",
	"kTW3BTZpCOLSyge75GsSQe2O51sOd3epd13kt99PZNuQX5C6PWYT8OaFvGwemdxcQSWdl/Mg/t58Y0vP",
	"62ocXCH/0G27/pNtX/9Pjh7P0VPjB+6o2v1Zg/lYJ8zuMENZJ+HwBWohc9bJXhMSms7qkCC5CDDXaMtX",
	"E1SYFUxj1asSHIatspm2CqR9bWYD1hQ8tJm5A5m4pEm1UxU/4QovxxX2t2tNeGH/kP/gKMOsVJae66kQ",
	"4MJZwSvwid8W9HDr/jbAw8Aqg6gFLHA8lHga1Ei3lJl58wmZV5GHuR16cdBilZdE3eJ79MltcmvdJhsb",
	"MH64uI2iuh6jMWpJqUikD/XDExIKyecs5glLMKo0CcgFZIufzjhhTRRy8bGQvIFdOgArqj1ct/dIfaTs",
	"06SGWN0DCGdIAcIpU6dYFZA6oNqqqdwYDqv2uRnMUnFiW/9U4ynKLjJTF7nmeRnMhzCc+SWtdp2ub7Re",
	"t0bWHitnUFgpPpRRdKWa0ODkWpNiUNiDr7C0LKK1hJWTvc1aFZ3XmupUvRc3oEvJxf/NsGr8UgRUq5uX",
	"CUYQ3Bzy83OU0wrwsMZ+/m0hyItclammvl92P6GwiwrzWstqVmlz5lfXqsaZAW5If7NDDx/Gyyog0MO5",
	"2abWlmBd4tK9rFvEbP3K4m4SDk4N1XpD+lrCgIhE2ZyWT/rbpmGvR+4E/ahXgDPU6pdXzxBMtjt0Tjif",
	"9QRUrlJLAU8e2/rrPEG4P7k/lPjm+M5SPejlyyePO62pfjN9K5pV3pB/dW3md4MtK548pgKDig1WM/mk",
	"uQQPqqO7UBEvSm27fLvb5zex+CQ+PomPa2m1UUmDphUCrpI09H45D/P5w+yEGtJAKmLK3SplOtofnWpd",
	"7N+9Sx+eCqX3v5h8MaGQmXt9L/jv4+YaMhjqfOEkh2t80bdxHzUw0XGldbcMvPoVdoH9N9SJJ845ImSV",
	"atI8W2eX9B//m992s+kN6w3c8qT0X2B7+fbaTLU7otiam7oFMGvebrui9F9bdTnFTpNT1xuZmvibEeaL",
	"X3Kq1arbCzfvbjqeBjbetjeNyzdVesXiAzBD3yw/ZYk4qNqMK5GxjBqB2A7joMoTLRlmzTiHNlcjvIxe",
	"E/UdG8hKNdtd1VDdvb/u7dx/v2sbpywwiO3A7EFA7Ez5GeW42PoC85EoYfFrzmOmzPCqbCNQuhEHErb7",
	"4/cAcs3yaGcJGNbCrGFWyMUHZauom2awU37mwHcor3jpbGpwk9AWx2XTh4oQW/NTZvvIB7Hhq64BhP5W",
	"AcS7obrAx4Ed99omAFZNNurBl7Ru2Tlh8fdlAQgZn7n57vrUqln4InjpphEMpGXDjlp8BDzjhA7mEpXJ",
	"RVMT2EEl142+jl6Zo0Xs86bSymQduPL7EJ/ijLxuDcqpXnxwaOGaucwqP9uJajzpB7aJeXUnxvDMzHMm",
	"USlBuEmBvKj61wp2mmo2t9LdMTzmU5TE3BMEYis2R8rh4s8xFUWnyXjF4Vz0+vz1+b8HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
